/** GENERATED by scripts/sync-brand-assets.ts. Do not edit manually. */
export declare const brandPalette: {
  readonly orange: "#A54200";
  readonly ink: "#172033";
  readonly white: "#FFFFFF";
  readonly mist: "#F7F8FA";
  readonly border: "#D8DDE5";
  readonly muted: "#5B6474";
};
