import { Collection, CollectionPillar } from './collection.types';

export const COLLECTION_PILLARS: CollectionPillar[] = [
  {
    id: 'all',
    label: 'Toutes les collections',
    shortLabel: 'Toutes',
    iconName: 'Sparkles',
    description: 'Explorez l’ensemble de nos sélections thématiques pour tous vos projets.',
  },
  {
    id: 'editorial',
    label: 'Tendances & Éditoriales',
    shortLabel: 'Tendances',
    iconName: 'TrendingUp',
    description: 'Les sélections coups de cœur de notre équipe et les pièces les plus prisées du moment.',
  },
  {
    id: 'budget',
    label: 'Bons plans & Petits prix',
    shortLabel: 'Petits prix',
    iconName: 'Tag',
    description: 'Des opportunités à prix doux, baisses de prix vérifiées et articles gratuits.',
  },
  {
    id: 'style',
    label: 'Styles, Vintage & Éco',
    shortLabel: 'Styles & Éco',
    iconName: 'Shirt',
    description: 'Design rétro, maroquinerie d’exception, savoir-faire français et seconde main durable.',
  },
  {
    id: 'lifestyle',
    label: 'Maison, Famille & Projets',
    shortLabel: 'Maison & Vie',
    iconName: 'Home',
    description: 'Aménager votre cocon, télétravailler dans les meilleures conditions ou équiper la famille.',
  },
  {
    id: 'mobility',
    label: 'Mobilité & Plein air',
    shortLabel: 'Mobilité',
    iconName: 'Bike',
    description: 'Vélos, véhicules économiques, équipements d’aventure et de saison.',
  },
  {
    id: 'local',
    label: 'Local & Professionnels',
    shortLabel: 'Local & Pros',
    iconName: 'MapPin',
    description: 'Vendeurs à proximité, boutiques professionnelles certifiées et remise en main propre.',
  },
  {
    id: 'personalized',
    label: 'Inspiré pour vous',
    shortLabel: 'Pour vous',
    iconName: 'Heart',
    description: 'Recommandations intelligentes basées sur vos envies et vos marques favorites.',
  },
];

export const ALL_COLLECTIONS: Collection[] = [
  // ==========================================
  // 1. TENDANCES & ÉDITORIALES
  // ==========================================
  {
    id: 'pepites-semaine',
    slug: 'pepites-semaine',
    pillarId: 'editorial',
    title: 'Les pépites de la semaine',
    shortTitle: 'Pépites de la semaine',
    subtitle: 'La sélection éditoriale coup de cœur de notre équipe parmi des milliers d’annonces.',
    description: 'Chaque semaine, notre équipe déniche pour vous les pièces les plus singulières, les meilleures affaires et les objets rares mis en ligne par des particuliers et pros de confiance.',
    curatorNote: 'Sélection renouvelée chaque lundi matin sur des critères stricts de qualité et de prix juste.',
    badge: { label: '✦ Coup de Cœur', variant: 'terracotta' },
    itemCountLabel: '50 pièces choisies',
    coverImageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
    tags: ['Sélection hebdo', 'Mobilier rare', 'High-tech', 'Mode'],
    filterCriteria: { isBoostedOnly: false, keywords: ['sélection', 'design', 'sézan', 'delonghi', 'sony', 'vintage'] },
    featuredListingIds: ['list-105', 'list-109', 'list-101'],
  },
  {
    id: 'bons-plans',
    slug: 'bons-plans',
    pillarId: 'editorial',
    title: 'Bons plans & Baisses de prix',
    shortTitle: 'Bons plans',
    subtitle: 'Des réductions réelles et des prix barrés sur des articles contrôlés.',
    description: 'Profitez de baisses de prix vérifiées sans fausses promotions. Tous les articles avec un prix d’origine barré pour maximiser votre pouvoir d’achat.',
    curatorNote: 'Historique de prix contrôlé pour certifier les vraies réductions de prix.',
    badge: { label: 'Jusqu’à -50%', variant: 'amber' },
    itemCountLabel: '1 400+ bonnes affaires',
    coverImageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&q=80',
    tags: ['Prix barré', 'Promotions', 'Moins cher', 'Déstockage'],
    filterCriteria: { isDiscounted: true },
    featuredListingIds: ['list-105', 'list-109'],
  },
  {
    id: 'nouveautes',
    slug: 'nouveautes',
    pillarId: 'editorial',
    title: 'Nouveautés du jour',
    shortTitle: 'Nouveautés',
    subtitle: 'Les dernières offres publiées au cours des dernières 24 heures.',
    description: 'Soyez les premiers sur les meilleures opportunités. Les annonces fraîches tout juste validées par notre système de modération.',
    curatorNote: 'Mise à jour en temps réel au fur et à mesure des publications des vendeurs.',
    badge: { label: 'Fraîchement publié', variant: 'sky' },
    itemCountLabel: '3 800+ nouvelles annonces',
    coverImageUrl: 'https://images.unsplash.com/photo-1522204523234-8729aa6e3d5f?auto=format&fit=crop&w=800&q=80',
    tags: ['Dernières 24h', 'Tout juste en ligne', 'Primeur'],
    filterCriteria: { keywords: [] },
  },
  {
    id: 'tendances',
    slug: 'tendances',
    pillarId: 'editorial',
    title: 'Tendances du moment sur Shongre',
    shortTitle: 'Tendances',
    subtitle: 'Les articles les plus recherchés, sauvegardés et consultés par la communauté.',
    description: 'Découvrez ce qui passionne les acheteurs cette semaine : objets cultes, appareils recherchés et pièces introuvables en magasin.',
    curatorNote: 'Calculé dynamiquement selon le volume de favoris et les prises de contact.',
    badge: { label: '🔥 En vogue', variant: 'rose' },
    itemCountLabel: '920+ articles phares',
    coverImageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
    tags: ['Recherches populaires', 'Plus consultés', 'Forte demande'],
    filterCriteria: { keywords: ['iphone', 'ps5', 'gravel', 'sézane', 'vintage'] },
  },
  {
    id: 'vedettes',
    slug: 'vedettes',
    pillarId: 'editorial',
    title: 'Vedettes Shongre',
    shortTitle: 'Vedettes',
    subtitle: 'Annonces à la une et mises en avant certifiées par nos vendeurs.',
    description: 'Des annonces premium bénéficiant d’une garantie visibilité et d’une conformité exemplaire sur le descriptif et les photos.',
    curatorNote: 'Présence certifiée en tête de recherche avec engagement de réponse rapide sous 2h.',
    badge: { label: '✦ À la Une', variant: 'terracotta' },
    itemCountLabel: '450+ annonces vedettes',
    coverImageUrl: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80',
    tags: ['Annonces certifiées', 'Garantie réponse', 'Mises en avant'],
    filterCriteria: { isBoostedOnly: true },
  },

  // ==========================================
  // 2. PRIX & BUDGET
  // ==========================================
  {
    id: 'moins-de-50',
    slug: 'moins-de-50',
    pillarId: 'budget',
    title: 'Pépites à moins de 50 €',
    shortTitle: 'Moins de 50 €',
    subtitle: 'Déco, jeux vidéo, mode et petit électroménager à prix ultra accessible.',
    description: 'Une sélection complète pour se faire plaisir sans compter. Des milliers d’articles en parfait état sous la barre des 50 euros.',
    curatorNote: 'Idéal pour chiner sans culpabiliser et dénicher des cadeaux abordables.',
    badge: { label: '≤ 50 €', variant: 'emerald' },
    itemCountLabel: '5 200+ articles',
    coverImageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=800&q=80',
    tags: ['Petit budget', 'Moins de 50€', 'Bons plans'],
    filterCriteria: { priceMax: 50, priceMin: 0.01 },
  },
  {
    id: 'moins-de-100',
    slug: 'moins-de-100',
    pillarId: 'budget',
    title: 'Sélection à moins de 100 €',
    shortTitle: 'Moins de 100 €',
    subtitle: 'Appareils testés, mobilier d’appoint et vêtements de marque à prix doux.',
    description: 'Le meilleur équilibre entre qualité supérieure et budget maîtrisé. Des équipements récents à une fraction du prix neuf.',
    curatorNote: 'Articles d’une valeur neuve moyenne de 200 à 350 € proposés sous les 100 €.',
    badge: { label: '≤ 100 €', variant: 'emerald' },
    itemCountLabel: '4 100+ articles',
    coverImageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80',
    tags: ['Budget malin', 'Moins de 100€', 'Qualité/Prix'],
    filterCriteria: { priceMax: 100, priceMin: 0.01 },
  },
  {
    id: 'dons-gratuit',
    slug: 'dons-gratuit',
    pillarId: 'budget',
    title: 'Dons & Objets gratuits',
    shortTitle: 'Dons gratuits',
    subtitle: 'Donnez une seconde vie aux objets : 100% gratuit et zéro déchet.',
    description: 'Des meubles, livres, plantes, matériaux et objets du quotidien offerts par des particuliers généreux à récupérer près de chez vous.',
    curatorNote: 'Encourage l’économie solidaire et circulaire. Aucune contrepartie financière exigée.',
    badge: { label: '🎁 100% Gratuit', variant: 'emerald' },
    itemCountLabel: '680+ dons disponibles',
    coverImageUrl: 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb7?auto=format&fit=crop&w=800&q=80',
    tags: ['Dons', 'Gratuit', 'Zéro déchet', 'Entraide'],
    filterCriteria: { isFreeDonation: true },
    featuredListingIds: ['list-110'],
  },
  {
    id: 'idees-cadeaux',
    slug: 'idees-cadeaux',
    pillarId: 'budget',
    title: 'Idées Cadeaux pour toutes les occasions',
    shortTitle: 'Idées cadeaux',
    subtitle: 'Anniversaires, fêtes, crémaillères : des attentions uniques pour tous les budgets.',
    description: 'Trouvez le cadeau parfait sans tomber dans le conventionnel : beaux livres d’art, jeux de société, maroquinerie, objets vintage et high-tech comme neufs.',
    curatorNote: 'Trié par idées originales avec emballage soigné ou boîte d’origine disponible.',
    badge: { label: '✨ Pour offrir', variant: 'amber' },
    itemCountLabel: '2 100+ suggestions',
    coverImageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80',
    tags: ['Cadeaux', 'Anniversaire', 'Fête des mères', 'Noël'],
    filterCriteria: { conditions: ['as_new', 'very_good'], keywords: ['cadeau', 'coffret', 'neuf', 'boîte'] },
  },
  {
    id: 'auto-moins-10k',
    slug: 'auto-moins-10k',
    pillarId: 'budget',
    title: 'Véhicules & Première voiture à moins de 10 000 €',
    shortTitle: 'Voitures < 10k€',
    subtitle: 'Citadines fiables, berlines économiques et premiers véhicules inspectés.',
    description: 'Idéal pour les jeunes conducteurs ou les trajets du quotidien : citadines sobres (Clio, 208, Polo, Yaris) avec contrôle technique valide et historique d’entretien transparent.',
    curatorNote: 'Véhicules avec contrôle technique de moins de 6 mois et historique de révision vérifié.',
    badge: { label: '≤ 10 000 €', variant: 'sky' },
    itemCountLabel: '1 100+ véhicules',
    coverImageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    tags: ['Citadines', 'Jeune permis', 'Économique', 'Contrôle Technique'],
    filterCriteria: { categorySlug: 'vehicules', priceMax: 10000 },
  },

  // ==========================================
  // 3. STYLES, VINTAGE & ÉCO
  // ==========================================
  {
    id: 'vintage-retro',
    slug: 'vintage-retro',
    pillarId: 'style',
    title: 'Design & Mobilier Vintage',
    shortTitle: 'Vintage & Rétro',
    subtitle: 'Pièces iconiques des années 60 à 90, chinées et certifiées par nos vendeurs.',
    description: 'Une sélection pointue de mobilier mid-century, assises rétro, luminaires d’époque et objets de décoration chinés auprès de passionnés et brocanteurs.',
    curatorNote: 'Chaque pièce porte une patine authentique et a été vérifiée par nos vendeurs passionnés.',
    badge: { label: 'Chiné & Vintage', variant: 'terracotta' },
    itemCountLabel: '840+ pépites',
    coverImageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
    tags: ['Mobilier rétro', 'Fauteuils', 'Déco chinée', 'Lampes', 'Scandinave'],
    filterCriteria: { categorySlug: 'maison-deco', keywords: ['vintage', 'rétro', 'design', 'scandinave', 'teck'] },
    featuredListingIds: ['list-109', 'list-110'],
  },
  {
    id: 'seconde-main-premium',
    slug: 'seconde-main-premium',
    pillarId: 'style',
    title: 'Seconde Main Premium & Créateurs',
    shortTitle: 'Premium & Luxe',
    subtitle: 'Maroquinerie de luxe, garde-robe soignée et montres d’exception.',
    description: 'Accédez aux plus belles maisons de couture et de design avec authenticité garantie. Des matières nobles, finitions haut de gamme et pièces d’exception à prix accessible.',
    curatorNote: 'Contrôle préalable des numéros de série, factures et certificats d’authenticité.',
    badge: { label: '💎 Premium', variant: 'purple' },
    itemCountLabel: '750+ pièces exclusives',
    coverImageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80',
    tags: ['Maroquinerie', 'Luxe', 'Créateurs', 'Sézane', 'Montres'],
    filterCriteria: { categorySlug: 'mode-beaute', keywords: ['sézan', 'laine', 'luxe', 'cuir', 'soie'] },
    featuredListingIds: ['list-105'],
  },
  {
    id: 'made-in-france',
    slug: 'made-in-france',
    pillarId: 'style',
    title: 'Made in France & Artisans Locaux',
    shortTitle: 'Made in France',
    subtitle: 'Créations régionales, ateliers français et savoir-faire traditionnel.',
    description: 'Soutenez les artisans, maroquiniers, céramistes et fabricants français. Des objets durables conçus dans nos régions avec passion et matières locales.',
    curatorNote: '100% fabriqué ou transformé dans les ateliers de nos régions françaises.',
    badge: { label: '🇫🇷 Fabriqué en France', variant: 'sky' },
    itemCountLabel: '620+ créations',
    coverImageUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80',
    tags: ['Fabrication française', 'Artisanat', 'Céramique', 'Cuir français'],
    filterCriteria: { keywords: ['france', 'artisan', 'fait main', 'atelier'] },
  },
  {
    id: 'reconditionne',
    slug: 'reconditionne',
    pillarId: 'style',
    title: 'Tech Reconditionnée & Apple à prix doux',
    shortTitle: 'Reconditionné',
    subtitle: 'Smartphones récents, ordinateurs, iPad et audio Hi-Fi testés avec garantie.',
    description: 'Le meilleur de la tech responsable. Des appareils inspectés sur plus de 35 points de contrôle, garantis jusqu’à 24 mois par nos ateliers partenaires.',
    curatorNote: 'Batteries testées au-delà de 85% de capacité d’origine, débloqués tous opérateurs.',
    badge: { label: '🌱 Garantie 12-24M', variant: 'emerald' },
    itemCountLabel: '1 250+ appareils',
    coverImageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80',
    tags: ['iPhone', 'MacBook', 'Audio Hi-Fi', 'iPad', 'Garantie'],
    filterCriteria: { categorySlug: 'multimedia', keywords: ['reconditionné', 'apple', 'iphone', 'macbook', 'garanti'] },
    featuredListingIds: ['list-101'],
  },
  {
    id: 'comme-neuf',
    slug: 'comme-neuf',
    pillarId: 'style',
    title: 'Articles Comme Neuf & Jamais Utilisé',
    shortTitle: 'Comme Neuf',
    subtitle: 'Produits sous blister, avec étiquette ou utilisés moins de 3 fois.',
    description: 'Profitez de la sensation du neuf au tarif de la seconde main. Les articles de cette sélection sont impeccables, souvent encore dans leur boîte d’origine.',
    curatorNote: 'Idéal pour ceux qui recherchent l’état parfait sans rayures ni traces d’usure.',
    badge: { label: 'État Parfait', variant: 'emerald' },
    itemCountLabel: '2 800+ articles',
    coverImageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    tags: ['Sous blister', 'Avec étiquette', 'Boîte d’origine'],
    filterCriteria: { conditions: ['as_new'] },
  },
  {
    id: 'eco-responsable',
    slug: 'eco-responsable',
    pillarId: 'style',
    title: 'Éco-responsable & Consommation Circulaire',
    shortTitle: 'Éco-responsable',
    subtitle: 'Objets réparables, durables et à faible impact environnemental.',
    description: 'Une démarche engagée pour prolonger la durée de vie des équipements, réduire l’empreinte carbone et consommer de manière éthique.',
    curatorNote: 'Calcul de l’impact CO2 économisé affiché sur chaque fiche article.',
    badge: { label: '♻️ Éco-Conçu', variant: 'emerald' },
    itemCountLabel: '1 900+ produits durables',
    coverImageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    tags: ['Circulaire', 'Durable', 'Faible impact', 'Réparable'],
    filterCriteria: { keywords: ['écologique', 'durable', 'bois', 'naturel', 'lin'] },
  },

  // ==========================================
  // 4. MAISON, FAMILLE & PROJETS DE VIE
  // ==========================================
  {
    id: 'premier-appartement',
    slug: 'premier-appartement',
    pillarId: 'lifestyle',
    title: 'Premier Appartement & Déménagement',
    shortTitle: 'Premier appart',
    subtitle: 'Électroménager compact, mobilier malin et équipement complet pour s’installer.',
    description: 'Tout ce dont vous avez besoin pour emménager sans exploser votre budget : canapés convertibles, micro-ondes, machines à laver, tables pliantes et vaisselle.',
    curatorNote: 'Packages d’équipements vérifiés avec option de livraison groupée à l’étage.',
    badge: { label: 'Pack Installation', variant: 'terracotta' },
    itemCountLabel: '2 400+ essentiels',
    coverImageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
    tags: ['Studio', 'Électroménager', 'Mobilier gain de place', 'Déménagement'],
    filterCriteria: { categorySlug: 'maison-deco', keywords: ['appartement', 'studio', 'machine', 'table', 'canapé'] },
  },
  {
    id: 'maison-cocooning',
    slug: 'maison-cocooning',
    pillarId: 'lifestyle',
    title: 'Maison Cocooning & Chaleureuse',
    shortTitle: 'Maison cocooning',
    subtitle: 'Canapés douillets, luminaires d’ambiance, plaids en laine et décoration cosy.',
    description: 'Transformez votre intérieur en havre de paix : fauteuils enveloppants, tapis berbères, lampes à poser tamisées et textures douces.',
    curatorNote: 'Sélection axée sur le confort thermique, l’acoustique et les matières douces.',
    badge: { label: 'Ambiance Cosy', variant: 'amber' },
    itemCountLabel: '1 600+ pièces',
    coverImageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80',
    tags: ['Canapés', 'Luminaires', 'Tapis', 'Textiles', 'Coussin'],
    filterCriteria: { categorySlug: 'maison-deco', keywords: ['canapé', 'fauteuil', 'lampe', 'plaid', 'tapis'] },
  },
  {
    id: 'teletravail',
    slug: 'teletravail',
    pillarId: 'lifestyle',
    title: 'Bureau & Espace Télétravail Ergonomique',
    shortTitle: 'Télétravail',
    subtitle: 'Bureaux assis-debout, chaises ergonomiques, moniteurs 4K et accessoires.',
    description: 'Améliorez votre productivité et votre confort au quotidien avec du matériel de bureau professionnel : fauteuils Herman Miller / Steelcase, écrans Dell / LG et stations d’accueil.',
    curatorNote: 'Équipements recommandés pour prévenir la fatigue visuelle et les douleurs lombaires.',
    badge: { label: 'Confort Pro', variant: 'sky' },
    itemCountLabel: '1 050+ équipements',
    coverImageUrl: 'https://images.unsplash.com/photo-1593062096033-9a26b09da705?auto=format&fit=crop&w=800&q=80',
    tags: ['Bureau assis-debout', 'Chaise ergonomique', 'Moniteur', 'Clavier'],
    filterCriteria: { keywords: ['bureau', 'chaise', 'écran', 'moniteur', 'ergonomique', 'clavier'] },
  },
  {
    id: 'setup-gaming',
    slug: 'setup-gaming',
    pillarId: 'lifestyle',
    title: 'Setup Gaming & Rétrogaming',
    shortTitle: 'Setup Gaming',
    subtitle: 'Consoles PS5/Xbox/Switch, PC Gamer, casques immersifs et sièges baquets.',
    description: 'Pour les passionnés de jeu vidéo : matériel puissant, consoles de dernière génération et perles rétrogaming révisées.',
    curatorNote: 'Consoles et cartes graphiques testées sous stress thermique avant validation.',
    badge: { label: '🎮 Ready to Play', variant: 'purple' },
    itemCountLabel: '1 350+ annonces',
    coverImageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    tags: ['PS5', 'Nintendo Switch', 'PC Gamer', 'Casque', 'Rétro'],
    filterCriteria: { categorySlug: 'multimedia', keywords: ['ps5', 'switch', 'gaming', 'carte graphique', 'console', 'arcade'] },
  },
  {
    id: 'famille-bebe',
    slug: 'famille-bebe',
    pillarId: 'lifestyle',
    title: 'Famille, Bébé & Puériculture',
    shortTitle: 'Famille & Bébé',
    subtitle: 'Poussettes tout-terrain, lits parapluie, sièges auto certifiés et jouets d’éveil.',
    description: 'Accompagnez la croissance de vos enfants avec du matériel de marque (Cybex, Bugaboo, Babyzen, Stokke) contrôlé et impeccable.',
    curatorNote: 'Vérification scrupuleuse des normes de sécurité européennes (ECE R129/i-Size).',
    badge: { label: 'Sécurité & Éveil', variant: 'rose' },
    itemCountLabel: '2 300+ articles',
    coverImageUrl: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80',
    tags: ['Poussettes', 'Sièges auto', 'Chambre bébé', 'Jeux d’éveil'],
    filterCriteria: { keywords: ['poussette', 'bébé', 'siège auto', 'yoyo', 'stokke', 'cybex'] },
  },
  {
    id: 'jardin-terrasse',
    slug: 'jardin-terrasse',
    pillarId: 'lifestyle',
    title: 'Jardin, Terrasse & Balcon',
    shortTitle: 'Jardin & Terrasse',
    subtitle: 'Salons de jardin, barbecues, parasols, outillage et plantes d’extérieur.',
    description: 'Créez votre coin de verdure : mobilier résistant aux intempéries (teck, aluminium, résine tressée), planchas, pots en terre cuite et tondeuses révisées.',
    curatorNote: 'Matériaux traités anti-corrosion et conçus pour durer face aux saisons.',
    badge: { label: 'Plein Soleil', variant: 'emerald' },
    itemCountLabel: '1 450+ équipements',
    coverImageUrl: 'https://images.unsplash.com/photo-1584467741267-b6e0b074529e?auto=format&fit=crop&w=800&q=80',
    tags: ['Salon de jardin', 'Barbecue', 'Planchas', 'Pots', 'Tondeuse'],
    filterCriteria: { categorySlug: 'maison-deco', keywords: ['jardin', 'terrasse', 'barbecue', 'plancha', 'pot', 'parasol'] },
  },
  {
    id: 'brico-weekend',
    slug: 'brico-weekend',
    pillarId: 'lifestyle',
    title: 'Brico & Outillage du Week-end',
    shortTitle: 'Brico & Outils',
    subtitle: 'Perceuses, scies circulaires, ponceuses et outillage professionnel robuste.',
    description: 'Pour tous vos travaux et rénovations maison : outils électroportatifs de marques leaders (Bosch Pro, Makita, DeWalt, Festool) prêts à l’emploi.',
    curatorNote: 'Moteurs et batteries testés en rotation avec contrôle des mandrins et charbons.',
    badge: { label: '🔧 Outils Pro', variant: 'amber' },
    itemCountLabel: '1 800+ outils',
    coverImageUrl: 'https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?auto=format&fit=crop&w=800&q=80',
    tags: ['Perceuse', 'Makita', 'Bosch Pro', 'Scie', 'Ponceuse'],
    filterCriteria: { keywords: ['perceuse', 'visseuse', 'makita', 'bosch', 'outil', 'scie', 'bricolage'] },
  },

  // ==========================================
  // 5. MOBILITÉ & SAISONS
  // ==========================================
  {
    id: 'mobilite-urbaine',
    slug: 'mobilite-urbaine',
    pillarId: 'mobility',
    title: 'Mobilité Urbaine & Vélo Électrique',
    shortTitle: 'Mobilité Urbaine',
    subtitle: 'Vélos de ville, gravel, trottinettes électriques et accessoires de sécurité.',
    description: 'Déplacez-vous rapidement, sans émissions et avec plaisir : vélos musculaires légers, vélos à assistance électrique (VAE) et casques aux normes.',
    curatorNote: 'Transmission, freins et pneus révisés avec gravage bicycode vérifié.',
    badge: { label: '🚴 Zéro Émission', variant: 'sky' },
    itemCountLabel: '1 750+ deux-roues',
    coverImageUrl: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=800&q=80',
    tags: ['Vélo électrique', 'Gravel', 'Trottinette', 'Casque', 'Antivol'],
    filterCriteria: { categorySlug: 'sports-loisirs', keywords: ['vélo', 'gravel', 'électrique', 'trottinette', 'vae'] },
  },
  {
    id: 'outdoor-aventure',
    slug: 'outdoor-aventure',
    pillarId: 'mobility',
    title: 'Outdoor, Randonnée & Bivouac',
    shortTitle: 'Outdoor & Bivouac',
    subtitle: 'Tentes légères, sacs de trekking, réchauds, vestes Gore-Tex et matériel de trail.',
    description: 'Équipez-vous pour vos escapades en pleine nature avec du matériel de montagne fiable (Osprey, The North Face, Salomon, Petzl, MSR).',
    curatorNote: 'Imperméabilité des toiles et zips étanches testés avant publication.',
    badge: { label: '🏔️ Grand Air', variant: 'sky' },
    itemCountLabel: '890+ équipements',
    coverImageUrl: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=80',
    tags: ['Tente', 'Randonnée', 'Trekking', 'Gore-Tex', 'Duvet'],
    filterCriteria: { categorySlug: 'sports-loisirs', keywords: ['tente', 'randonnée', 'sac à dos', 'trek', 'bivouac', 'gore-tex'] },
  },
  {
    id: 'saison-actuelle',
    slug: 'saison-actuelle',
    pillarId: 'mobility',
    title: 'Sélection de Saison & Événements',
    shortTitle: 'Sélection de Saison',
    subtitle: 'Vêtements de saison, équipements météo et sélections adaptées aux événements du moment.',
    description: 'Une collection dynamique qui s’adapte au fil des mois : rentrée, sports d’hiver, escapades d’été ou festivités de fin d’année.',
    curatorNote: 'Renouvelée au rythme des saisons et des grands temps forts de l’année.',
    badge: { label: '☀️ Éphémère', variant: 'amber' },
    itemCountLabel: '2 100+ pièces adaptées',
    coverImageUrl: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80',
    tags: ['Saison', 'Manteaux', 'Équipement météo', 'Week-end'],
    filterCriteria: { keywords: ['manteau', 'laine', 'ski', 'vacances', 'saison'] },
  },

  // ==========================================
  // 6. LOCAL & PROFESSIONNELS
  // ==========================================
  {
    id: 'pres-de-chez-vous',
    slug: 'pres-de-chez-vous',
    pillarId: 'local',
    title: 'Près de chez vous & Remise Immédiate',
    shortTitle: 'Près de chez vous',
    subtitle: 'Annonces locales disponibles pour un retrait immédiat en main propre.',
    description: 'Rencontrez vos voisins, testez l’article sur place et repartez avec dès aujourd’hui sans frais ni délais de transport.',
    curatorNote: 'Favorise les échanges de quartier sécurisés et les rendez-vous en lieux publics.',
    badge: { label: '📍 Retrait Direct', variant: 'terracotta' },
    itemCountLabel: 'Disponible aujourd’hui',
    coverImageUrl: 'https://images.unsplash.com/photo-1524813686514-a57563d77d66?auto=format&fit=crop&w=800&q=80',
    tags: ['Main propre', 'Local', 'Sans frais de port', 'Immédiat'],
    filterCriteria: { keywords: ['lyon', 'paris', 'bordeaux', 'marseille', 'nantes'] },
  },
  {
    id: 'pros-certifies',
    slug: 'pros-certifies',
    pillarId: 'local',
    title: 'Boutiques Pro & Vendeurs les Mieux Notés',
    shortTitle: 'Boutiques Pro',
    subtitle: 'Commerces vérifiés, concessionnaires officiels et vendeurs à plus de 4.8/5.',
    description: 'Achetez en toute sérénité auprès d’artisans, de boutiques officielles et de vendeurs particuliers reconnus pour leur sérieux et leurs emballages soignés.',
    curatorNote: 'Profils contrôlés avec SIRET valide ou historique supérieur à 20 avis 5 étoiles.',
    badge: { label: '🛡️ Vendeurs Certifiés', variant: 'emerald' },
    itemCountLabel: '850+ boutiques partenaires',
    coverImageUrl: 'https://images.unsplash.com/photo-1556742049-0a67e557224f?auto=format&fit=crop&w=800&q=80',
    tags: ['Boutique Pro', 'Avis vérifiés', 'Facture avec TVA', 'Garantie'],
    filterCriteria: { isProOnly: true },
  },
  {
    id: 'livraison-directe',
    slug: 'livraison-directe',
    pillarId: 'local',
    title: 'Livraison Express & Paiement Sécurisé Shongre',
    shortTitle: 'Livraison directe',
    subtitle: 'Articles éligibles à l’envoi mondial relay / Colissimo avec garantie acheteur.',
    description: 'Commandez en 1 clic depuis toute la France. Les fonds sont sécurisés sous séquestre jusqu’à la confirmation de réception de votre colis.',
    curatorNote: 'Protection acheteur Shongre incluant remboursement intégral en cas de colis non conforme.',
    badge: { label: '📦 Livraison France', variant: 'indigo' },
    itemCountLabel: '6 500+ articles expédiables',
    coverImageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    tags: ['Mondial Relay', 'Colissimo', 'Paiement sécurisé', 'Protection acheteur'],
    filterCriteria: { hasDelivery: true },
  },

  // ==========================================
  // 7. PERSONNALISÉ
  // ==========================================
  {
    id: 'vous-aimerez-aussi',
    slug: 'vous-aimerez-aussi',
    pillarId: 'personalized',
    title: 'Inspiré de vos Recherches & Favoris',
    shortTitle: 'Pour vous',
    subtitle: 'Suggestions intelligentes calculées selon vos consultations et marques favorites.',
    description: 'Une collection sur-mesure qui évolue avec vos goûts : retrouvez les pièces similaires à vos coups de cœur et les alertes nouveautés personnalisées.',
    curatorNote: 'Algorithme d’affinité local et privé respectant strictement votre vie privée.',
    badge: { label: '🎯 Sur-Mesure', variant: 'rose' },
    itemCountLabel: 'Personnalisé pour vous',
    coverImageUrl: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=80',
    tags: ['Recommandations', 'Marques favorites', 'Similaires', 'Sur-mesure'],
    filterCriteria: { keywords: ['sézane', 'delonghi', 'sony', 'vintage', 'gravel'] },
  },
];

export function getCollectionBySlug(slug?: string): Collection | undefined {
  if (!slug) return undefined;
  return ALL_COLLECTIONS.find((c) => c.slug === slug || c.id === slug);
}

export function getCollectionsByPillar(pillarId: string): Collection[] {
  if (!pillarId || pillarId === 'all') return ALL_COLLECTIONS;
  return ALL_COLLECTIONS.filter((c) => c.pillarId === pillarId);
}
