const IDENTIFIER_LABELS: Readonly<Record<string, string>> = {
  active: "Actif",
  inactive: "Inactif",
  draft: "Brouillon",
  published: "Publié",
  archived: "Archivé",
  pending: "En attente",
  pending_review: "En cours d’examen",
  pending_approval: "À approuver",
  approved: "Approuvé",
  scheduled: "Planifié",
  disabled: "Désactivé",
  paused: "En pause",
  expired: "Expiré",
  cancelled: "Annulé",
  completed: "Terminé",
  completed_with_errors: "Terminé avec erreurs",
  failed: "Échec",
  queued: "En attente",
  validating: "Validation en cours",
  processing: "Traitement en cours",
  partial: "Partiel",
  preview: "Aperçu",
  proposed: "Proposé",
  confirmed: "Confirmé",
  rescheduled: "Replanifié",
  requested: "Demandé",
  in_transit: "En transit",
  invited: "Invité",
  suspended: "Suspendu",
  revoked: "Révoqué",
  trialing: "Période d’essai",
  past_due: "Paiement en retard",
  open: "Ouvert",
  paid: "Payé",
  void: "Annulé",
  uncollectible: "Irrécouvrable",
  created: "Créé",
  requires_action: "Action requise",
  succeeded: "Réussi",
  partially_refunded: "Partiellement remboursé",
  refunded: "Remboursé",
  consumed: "Utilisé",
  incomplete: "Incomplet",
  cancellation_pending: "Résiliation programmée",

  owner: "Propriétaire",
  admin: "Administrateur",
  manager: "Responsable",
  seller: "Vendeur",
  support: "Assistance",
  analyst: "Analyste",
  billing_admin: "Gestionnaire de facturation",
  recruitment_admin: "Administrateur du recrutement",
  recruiter: "Recruteur",
  hiring_manager: "Responsable du recrutement",
  interviewer: "Chargé d’entretien",

  guest: "Visiteur",
  individual: "Particulier",
  professional: "Professionnel",
  organization: "Organisation",
  dealer: "Concessionnaire",
  all: "Tous",
  new: "Nouveau client",
  existing: "Client existant",

  free: "Gratuit",
  pack: "Pack",
  subscription: "Abonnement",
  custom: "Sur mesure",
  exclusive: "Non cumulable",
  best_only: "Meilleure remise uniquement",
  stackable: "Cumulable",
  coupon: "Code promotionnel",
  automatic: "Automatique",
  admin_grant: "Attribution administrative",
  fixed: "Montant fixe",
  percentage: "Pourcentage",
  introductory_price: "Tarif de lancement",
  free_period: "Période offerte",
  generic_subscription: "Abonnement Shongre Pro",
  auto_subscription: "Abonnement Auto",
  immo_subscription: "Abonnement Immo",
  employment_subscription: "Abonnement Emploi",
  education_subscription: "Abonnement Éducation",
  courses_subscription: "Abonnement Éducation",
  addon: "Option complémentaire",
  promotion: "Promotion",
  marketplace_service: "Service marketplace",

  demo: "Démonstration",
  sandbox: "Bac à sable",
  production: "Production",
  stripe: "Stripe",

  csv: "CSV",
  xml: "XML",
  api: "API",
  json_api: "API JSON",
  ats: "ATS",
  career_site: "Site carrière",

  phone: "Téléphone",
  video: "Visioconférence",
  in_person: "En personne",

  email: "Adresse e-mail",
  identity: "Identité",
  business: "Entreprise",
  bank_payout: "Compte de versement",
  mfa: "Authentification multifacteur",
  not_started: "Non commencé",
  verified: "Vérifié",
  rejected: "Refusé",

  compliant: "Conforme",
  suspicious: "Suspect",
  prohibited_item: "Objet interdit",
  potential_scam: "Arnaque potentielle",

  secure_sale: "Vente sécurisée",
  urgent: "Urgent",
  search_bump: "Remonter l’annonce",
  featured: "À la une",
  homepage_spotlight: "Mise en avant sur l’accueil",
  category_spotlight: "Mise en avant dans la catégorie",
  qualified_lead: "Demande qualifiée",
  sponsored_dealer: "Concessionnaire sponsorisé",
  inspection_referral: "Mise en relation inspection",
  warranty_referral: "Mise en relation garantie",
  financing_referral: "Mise en relation financement",
  insurance_referral: "Mise en relation assurance",
  delivery_referral: "Mise en relation livraison",
  trade_in_referral: "Mise en relation reprise",
  extra_vehicle_pack: "Pack de véhicules supplémentaires",
  lead_credit_pack: "Pack de demandes qualifiées",

  maxActiveJobs: "Offres actives maximum",
  maxRecruiterSeats: "Comptes recruteurs maximum",
  maxBranches: "Agences maximum",
  maxClients: "Employeurs clients maximum",
  maxPipelines: "Pipelines maximum",
  basicAnalytics: "Statistiques essentielles",
  advancedAnalytics: "Statistiques avancées",
  reusableTemplates: "Modèles réutilisables",
  candidateAssignment: "Attribution des candidatures",
  privateRecruiterNotes: "Notes recruteur privées",
  interviewScheduling: "Planification des entretiens",
  talentPool: "Vivier de candidats",
  csvImport: "Import CSV",
  xmlImport: "Import XML",
  apiSync: "Synchronisation API",
  atsIntegrations: "Intégrations ATS",
  ssoFramework: "Authentification SSO",
  centralizedBilling: "Facturation centralisée",
  includedPromotionCredits: "Crédits de visibilité inclus",

  "job.manage": "Gérer les offres",
  "application.manage": "Gérer les candidatures",
  "interview.manage": "Gérer les entretiens",
  "team.manage": "Gérer l’équipe",
  "courses.manage": "Gérer les cours",
  "courses.manage.own": "Gérer ses cours",
  "leads.manage": "Gérer les demandes",
  "leads.respond.own": "Répondre à ses demandes",
  "billing.manage": "Gérer la facturation",
  "offers:read": "Consulter les cours",
  "leads:respond": "Répondre aux demandes",
  "workspace:read": "Consulter l’espace organisme",

  eligible: "Éligibilité",
  reasonCode: "Motif",
  quotaLimit: "Quota",
  quotaPeriodDays: "Période du quota",
  durationDays: "Durée",
  baseAmountMinor: "Montant de base",
  minimumAmountMinor: "Montant minimum",
  maximumAmountMinor: "Montant maximum",
  fixedAdjustmentMinor: "Ajustement fixe",
  percentageAdjustmentBps: "Ajustement en pourcentage",
  feeRateBps: "Taux de frais",
  fixedFeeMinor: "Frais fixes",
  taxRateBps: "Taux de taxe",
  entitlementKey: "Droit accordé",
  entitlementValue: "Valeur du droit",
};

const ACRONYMS: Readonly<Record<string, string>> = {
  ai: "IA",
  api: "API",
  ats: "ATS",
  csv: "CSV",
  id: "ID",
  kyc: "KYC",
  kyb: "KYB",
  sso: "SSO",
  xml: "XML",
};

export function humanizeIdentifier(identifier: string): string {
  const words = identifier
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/[._-]+/g, " ")
    .split(/\s+/)
    .filter(Boolean)
    .map((word) => ACRONYMS[word.toLowerCase()] || word.toLowerCase());

  if (words.length === 0) return "—";
  const label = words.join(" ");
  return label.charAt(0).toUpperCase() + label.slice(1);
}

export function labelIdentifier(identifier: string): string {
  return IDENTIFIER_LABELS[identifier] || humanizeIdentifier(identifier);
}
