#!/usr/bin/env node

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  themeAspect,
  themeBorders,
  themeBreakpoints,
  themeColors,
  themeContainers,
  themeFontFamilies,
  themeFontWeights,
  themeGridTemplates,
  themeLetterSpacing,
  themeLineHeights,
  themeMotion,
  themeOpacity,
  themeRadii,
  themeShadows,
  themeSpaceScale,
  themeSpacing,
  themeText,
  themeTextLineHeights,
  themeZIndex,
} from "../src/theme.ts";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = resolve(packageRoot, "dist/tokens.css");

const declarations = [];
const add = (name, value) => declarations.push(`  --${name}: ${value};`);

for (const [name, value] of Object.entries(themeColors))
  add(`color-${name}`, value);
for (const [name, value] of Object.entries(themeRadii))
  add(`radius-${name}`, value);
for (const [name, value] of Object.entries(themeText)) {
  add(`text-${name}`, value);
  add(`text-${name}--line-height`, themeTextLineHeights[name]);
}
for (const [name, value] of Object.entries(themeFontFamilies))
  add(`font-${name}`, name === "sans" ? "var(--font-family-sans)" : value);
for (const [name, value] of Object.entries(themeFontWeights))
  add(`font-weight-${name}`, value);
for (const [name, value] of Object.entries(themeLineHeights))
  add(`leading-${name}`, value);
for (const [name, value] of Object.entries(themeLetterSpacing))
  add(`tracking-${name}`, value);
add("spacing", themeSpacing.base);
for (const [name, value] of Object.entries(themeSpacing)) {
  if (name !== "base") add(`spacing-${name}`, value);
}
for (const [name, value] of Object.entries(themeSpaceScale))
  add(`spacing-semantic-${name}`, value);
for (const [name, value] of Object.entries(themeContainers))
  add(`container-${name}`, value);
for (const [name, value] of Object.entries(themeGridTemplates))
  add(`grid-template-columns-${name}`, value);
for (const [name, value] of Object.entries(themeBreakpoints))
  add(`breakpoint-${name}`, value);
for (const [name, value] of Object.entries(themeShadows))
  add(`shadow-${name}`, value);
for (const [name, value] of Object.entries(themeMotion)) add(name, value);
for (const [name, value] of Object.entries(themeOpacity))
  add(`opacity-${name}`, value);
for (const [name, value] of Object.entries(themeBorders))
  add(`border-${name}`, value);
for (const [name, value] of Object.entries(themeAspect))
  add(`aspect-${name}`, value);

const root = [
  "  --design-system-contract-version: 5;",
  `  --font-family-sans: ${themeFontFamilies.sans};`,
  ...Object.entries(themeZIndex).map(
    ([name, value]) => `  --z-${name}: ${value};`,
  ),
  "  --mobile-nav-h: var(--spacing-mobile-nav-height);",
  "  --mobile-nav-fab-rise: var(--spacing-mobile-nav-fab-rise);",
  "  --mobile-nav-total-h: calc(var(--mobile-nav-h) + var(--mobile-nav-fab-rise) + var(--border-hairline) + env(safe-area-inset-bottom));",
];

const css = `/* GENERATED by @shongre/design-tokens. Edit src/theme.ts, then run make tokens-build. */\n@theme {\n${declarations.join("\n")}\n}\n\n:root {\n${root.join("\n")}\n}\n`;
const checkOnly = process.argv.includes("--check");

if (checkOnly) {
  let existing = "";
  try {
    existing = readFileSync(outputPath, "utf8");
  } catch {
    // Report the same actionable drift message as a content mismatch.
  }
  if (existing !== css) {
    console.error(
      "Generated design-token CSS is stale. Run make tokens-build.",
    );
    process.exit(1);
  }
  console.log("Design-token CSS is generated from the canonical package.");
  process.exit(0);
}

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, css);
console.log(`Generated ${outputPath}`);
