/**
 * SHONGRE CANONICAL ATTRIBUTE REGISTRY
 * Reusable, typed attribute definitions across all marketplace domains.
 */

import { TaxonomyAttribute } from "./taxonomy.types";

export const ATTRIBUTE_REGISTRY: Record<string, TaxonomyAttribute> = {
  // ==========================================
  // SHARED & GENERAL ATTRIBUTES
  // ==========================================
  "product.brand": {
    id: "product.brand",
    code: "brand",
    label: "Marque",
    dataType: "text",
    required: false,
    filterable: true,
    searchable: true,
    publicationGroup: "general",
    displayOrder: 1,
    helpText: "Indiquez la marque ou le fabricant de l'article.",
  },
  "product.model": {
    id: "product.model",
    code: "model",
    label: "Modèle",
    dataType: "text",
    required: false,
    filterable: true,
    searchable: true,
    publicationGroup: "general",
    displayOrder: 2,
    helpText: "Modèle ou référence exacte du produit.",
  },
  "product.color": {
    id: "product.color",
    code: "color",
    label: "Couleur principale",
    dataType: "select",
    required: false,
    filterable: true,
    publicationGroup: "general",
    displayOrder: 3,
    options: [
      { value: "noir", label: "Noir" },
      { value: "blanc", label: "Blanc" },
      { value: "gris", label: "Gris / Argent" },
      { value: "bleu", label: "Bleu" },
      { value: "rouge", label: "Rouge" },
      { value: "vert", label: "Vert" },
      { value: "jaune", label: "Jaune / Doré" },
      { value: "marron", label: "Marron / Beige" },
      { value: "rose", label: "Rose / Violet" },
      { value: "multicolore", label: "Multicolore" },
    ],
  },
  "product.material": {
    id: "product.material",
    code: "material",
    label: "Matière",
    dataType: "select",
    required: false,
    filterable: true,
    publicationGroup: "specifications",
    displayOrder: 4,
    options: [
      { value: "bois", label: "Bois massif" },
      { value: "metal", label: "Métal / Acier" },
      { value: "cuir", label: "Cuir véritable" },
      { value: "simili_cuir", label: "Simili cuir / PU" },
      { value: "tissu", label: "Tissu / Coton / Lin" },
      { value: "verre", label: "Verre" },
      { value: "plastique", label: "Plastique / PVC" },
      { value: "ceramique", label: "Céramique / Grès" },
      { value: "marbre", label: "Marbre / Pierre" },
      { value: "autre", label: "Autre matière" },
    ],
  },
  "product.warranty_months": {
    id: "product.warranty_months",
    code: "warranty_months",
    label: "Garantie restante",
    dataType: "number",
    unit: "mois",
    required: false,
    filterable: true,
    publicationGroup: "legal",
    displayOrder: 9,
    validation: { min: 0, max: 120 },
  },

  // ==========================================
  // VEHICLES & MOBILITY
  // ==========================================
  "vehicle.brand": {
    id: "vehicle.brand",
    code: "vehicle_brand",
    label: "Marque du véhicule",
    dataType: "select",
    required: true,
    filterable: true,
    searchable: true,
    publicationGroup: "general",
    displayOrder: 1,
    options: [
      { value: "peugeot", label: "Peugeot" },
      { value: "renault", label: "Renault" },
      { value: "citroen", label: "Citroën" },
      { value: "volkswagen", label: "Volkswagen" },
      { value: "audi", label: "Audi" },
      { value: "bmw", label: "BMW" },
      { value: "mercedes", label: "Mercedes-Benz" },
      { value: "toyota", label: "Toyota" },
      { value: "tesla", label: "Tesla" },
      { value: "ford", label: "Ford" },
      { value: "fiat", label: "Fiat" },
      { value: "nissan", label: "Nissan" },
      { value: "hyundai", label: "Hyundai" },
      { value: "kia", label: "Kia" },
      { value: "seat", label: "Seat" },
      { value: "skoda", label: "Škoda" },
      { value: "dacia", label: "Dacia" },
      { value: "volvo", label: "Volvo" },
      { value: "porsche", label: "Porsche" },
      { value: "mini", label: "Mini" },
      { value: "honda", label: "Honda" },
      { value: "yamaha", label: "Yamaha" },
      { value: "kawasaki", label: "Kawasaki" },
      { value: "ducati", label: "Ducati" },
      { value: "autre", label: "Autre marque" },
    ],
  },
  "vehicle.model": {
    id: "vehicle.model",
    code: "vehicle_model",
    label: "Modèle",
    dataType: "text",
    required: true,
    filterable: true,
    searchable: true,
    publicationGroup: "general",
    displayOrder: 2,
    validation: { placeholder: "ex: 208, Clio V, Golf 8, Model 3" },
  },
  "vehicle.year": {
    id: "vehicle.year",
    code: "year",
    label: "Année-modèle",
    dataType: "year",
    unit: "an",
    required: true,
    filterable: true,
    sortable: true,
    publicationGroup: "general",
    displayOrder: 3,
    validation: { min: 1950, max: 2026 },
  },
  "vehicle.mileage": {
    id: "vehicle.mileage",
    code: "mileage",
    label: "Kilométrage",
    dataType: "number",
    unit: "km",
    required: true,
    filterable: true,
    sortable: true,
    publicationGroup: "general",
    displayOrder: 4,
    validation: { min: 0, max: 1000000 },
  },
  "vehicle.body_type": {
    id: "vehicle.body_type",
    code: "body_type",
    label: "Carrosserie / Silhouette",
    dataType: "select",
    required: true,
    filterable: true,
    publicationGroup: "specifications",
    displayOrder: 5,
    options: [
      { value: "citadine", label: "Citadine" },
      { value: "berline", label: "Berline" },
      { value: "break", label: "Break" },
      { value: "suv", label: "SUV / 4x4" },
      { value: "coupe", label: "Coupé" },
      { value: "cabriolet", label: "Cabriolet" },
      { value: "monospace", label: "Monospace" },
      { value: "utilitaire", label: "Utilitaire / Fourgon" },
      { value: "pickup", label: "Pick-up" },
      { value: "sans_permis", label: "Voiture sans permis" },
    ],
  },
  "vehicle.fuel": {
    id: "vehicle.fuel",
    code: "fuel",
    label: "Carburant / Énergie",
    dataType: "select",
    required: true,
    filterable: true,
    publicationGroup: "performance",
    displayOrder: 6,
    options: [
      { value: "essence", label: "Essence" },
      { value: "diesel", label: "Diesel" },
      { value: "hybride", label: "Hybride (essence/électrique)" },
      { value: "hybride_rechargeable", label: "Hybride rechargeable (PHEV)" },
      { value: "electrique", label: "100% Électrique" },
      { value: "gpl", label: "GPL / Bioéthanol (E85)" },
      { value: "hydrogene", label: "Hydrogène" },
    ],
  },
  "vehicle.gearbox": {
    id: "vehicle.gearbox",
    code: "gearbox",
    label: "Boîte de vitesse",
    dataType: "select",
    required: true,
    filterable: true,
    publicationGroup: "performance",
    displayOrder: 7,
    options: [
      { value: "manuelle", label: "Manuelle" },
      { value: "automatique", label: "Automatique" },
    ],
  },
  "vehicle.critair": {
    id: "vehicle.critair",
    code: "critair",
    label: "Vignette Crit'Air",
    dataType: "select",
    required: false,
    filterable: true,
    publicationGroup: "legal",
    displayOrder: 8,
    options: [
      { value: "0", label: "Crit'Air 0 (Électrique / Hydrogène)" },
      { value: "1", label: "Crit'Air 1 (Euro 5/6 essence, hybrides)" },
      { value: "2", label: "Crit'Air 2 (Euro 4 essence, Euro 5/6 diesel)" },
      { value: "3", label: "Crit'Air 3 (Euro 2/3 essence, Euro 4 diesel)" },
      { value: "4", label: "Crit'Air 4 (Euro 3 diesel)" },
      { value: "5", label: "Crit'Air 5 (Euro 2 diesel)" },
      { value: "non_classe", label: "Non classé" },
    ],
  },
  "vehicle.doors": {
    id: "vehicle.doors",
    code: "doors",
    label: "Nombre de portes",
    dataType: "select",
    required: false,
    filterable: true,
    publicationGroup: "specifications",
    displayOrder: 9,
    options: [
      { value: "2", label: "2 portes" },
      { value: "3", label: "3 portes" },
      { value: "4", label: "4 portes" },
      { value: "5", label: "5 portes" },
      { value: "6_plus", label: "6 portes ou plus" },
    ],
  },
  "vehicle.seats": {
    id: "vehicle.seats",
    code: "seats",
    label: "Nombre de places",
    dataType: "number",
    required: false,
    filterable: true,
    publicationGroup: "specifications",
    displayOrder: 10,
    validation: { min: 1, max: 9 },
  },
  "vehicle.fiscal_power": {
    id: "vehicle.fiscal_power",
    code: "fiscal_power",
    label: "Puissance fiscale",
    dataType: "number",
    unit: "CV",
    required: false,
    filterable: true,
    publicationGroup: "performance",
    displayOrder: 11,
    validation: { min: 1, max: 100 },
  },
  "vehicle.engine_power_din": {
    id: "vehicle.engine_power_din",
    code: "engine_power_din",
    label: "Puissance DIN",
    dataType: "number",
    unit: "ch",
    required: false,
    filterable: true,
    publicationGroup: "performance",
    displayOrder: 12,
    validation: { min: 10, max: 1500 },
  },
  "vehicle.battery_capacity": {
    id: "vehicle.battery_capacity",
    code: "battery_capacity",
    label: "Capacité de batterie",
    dataType: "number",
    unit: "kWh",
    required: false,
    filterable: true,
    publicationGroup: "performance",
    displayOrder: 13,
    dependencies: [
      {
        attributeId: "vehicle.fuel",
        operator: "in",
        value: ["electrique", "hybride_rechargeable"],
      },
    ],
    validation: { min: 1, max: 250 },
  },
  "vehicle.electric_range": {
    id: "vehicle.electric_range",
    code: "electric_range",
    label: "Autonomie WLTP",
    dataType: "number",
    unit: "km",
    required: false,
    filterable: true,
    publicationGroup: "performance",
    displayOrder: 14,
    dependencies: [
      {
        attributeId: "vehicle.fuel",
        operator: "in",
        value: ["electrique", "hybride_rechargeable"],
      },
    ],
    validation: { min: 10, max: 1200 },
  },
  "vehicle.first_hand": {
    id: "vehicle.first_hand",
    code: "first_hand",
    label: "Première main",
    dataType: "boolean",
    required: false,
    filterable: true,
    publicationGroup: "general",
    displayOrder: 15,
  },

  // ==========================================
  // REAL ESTATE / IMMOBILIER
  // ==========================================
  "real_estate.property_type": {
    id: "real_estate.property_type",
    code: "property_type",
    label: "Type de bien",
    dataType: "select",
    required: true,
    filterable: true,
    publicationGroup: "general",
    displayOrder: 1,
    options: [
      { value: "appartement", label: "Appartement" },
      { value: "maison", label: "Maison" },
      { value: "villa", label: "Villa" },
      { value: "studio", label: "Studio" },
      { value: "loft", label: "Loft / Atelier" },
      { value: "duplex", label: "Duplex / Triplex" },
      { value: "chalet", label: "Chalet" },
      { value: "ferme", label: "Ferme / Corps de ferme" },
      { value: "terrain", label: "Terrain constructible" },
      { value: "parking", label: "Parking / Garage / Box" },
      { value: "immeuble", label: "Immeuble de rapport" },
      { value: "bureau", label: "Bureau" },
      { value: "commerce", label: "Local commercial / Boutique" },
      { value: "entrepot", label: "Entrepôt / Hangar" },
    ],
  },
  "real_estate.surface": {
    id: "real_estate.surface",
    code: "surface",
    label: "Surface habitable",
    dataType: "number",
    unit: "m²",
    required: true,
    filterable: true,
    sortable: true,
    publicationGroup: "dimensions",
    displayOrder: 2,
    validation: { min: 5, max: 10000 },
  },
  "real_estate.land_surface": {
    id: "real_estate.land_surface",
    code: "land_surface",
    label: "Surface du terrain",
    dataType: "number",
    unit: "m²",
    required: false,
    filterable: true,
    publicationGroup: "dimensions",
    displayOrder: 3,
    validation: { min: 0, max: 500000 },
  },
  "real_estate.rooms": {
    id: "real_estate.rooms",
    code: "rooms",
    label: "Nombre de pièces",
    dataType: "select",
    required: true,
    filterable: true,
    publicationGroup: "specifications",
    displayOrder: 4,
    options: [
      { value: "1", label: "1 pièce (Studio/T1)" },
      { value: "2", label: "2 pièces (T2)" },
      { value: "3", label: "3 pièces (T3)" },
      { value: "4", label: "4 pièces (T4)" },
      { value: "5", label: "5 pièces (T5)" },
      { value: "6_plus", label: "6 pièces et plus" },
    ],
  },
  "real_estate.bedrooms": {
    id: "real_estate.bedrooms",
    code: "bedrooms",
    label: "Nombre de chambres",
    dataType: "number",
    required: false,
    filterable: true,
    publicationGroup: "specifications",
    displayOrder: 5,
    validation: { min: 0, max: 30 },
  },
  "real_estate.furnished": {
    id: "real_estate.furnished",
    code: "furnished",
    label: "Meublé",
    dataType: "select",
    required: false,
    filterable: true,
    publicationGroup: "specifications",
    displayOrder: 6,
    options: [
      { value: "meuble", label: "Meublé" },
      { value: "non_meuble", label: "Non meublé" },
    ],
  },
  "real_estate.energy_class": {
    id: "real_estate.energy_class",
    code: "energy_class",
    label: "Classe énergétique (DPE)",
    dataType: "select",
    required: false,
    filterable: true,
    publicationGroup: "legal",
    displayOrder: 7,
    options: [
      { value: "A", label: "A (≤ 70 kWh/m²/an)" },
      { value: "B", label: "B (71 à 110)" },
      { value: "C", label: "C (111 à 180)" },
      { value: "D", label: "D (181 à 250)" },
      { value: "E", label: "E (251 à 330)" },
      { value: "F", label: "F (331 à 420 - Passoire)" },
      { value: "G", label: "G (> 420 - Passoire)" },
      { value: "non_soumis", label: "Vierge / Non soumis" },
    ],
  },
  "real_estate.ges_class": {
    id: "real_estate.ges_class",
    code: "ges_class",
    label: "Émissions GES",
    dataType: "select",
    required: false,
    filterable: true,
    publicationGroup: "legal",
    displayOrder: 8,
    options: [
      { value: "A", label: "A (≤ 6 kg CO2/m²/an)" },
      { value: "B", label: "B (7 à 11)" },
      { value: "C", label: "C (12 à 30)" },
      { value: "D", label: "D (31 à 50)" },
      { value: "E", label: "E (51 à 70)" },
      { value: "F", label: "F (71 à 100)" },
      { value: "G", label: "G (> 100)" },
    ],
  },
  "real_estate.floor": {
    id: "real_estate.floor",
    code: "floor",
    label: "Étage",
    dataType: "number",
    required: false,
    publicationGroup: "specifications",
    displayOrder: 9,
    validation: { min: -2, max: 100 },
  },
  "real_estate.elevator": {
    id: "real_estate.elevator",
    code: "elevator",
    label: "Ascenseur",
    dataType: "boolean",
    required: false,
    filterable: true,
    publicationGroup: "specifications",
    displayOrder: 10,
  },
  "real_estate.balcony_terrace": {
    id: "real_estate.balcony_terrace",
    code: "balcony_terrace",
    label: "Balcon / Terrasse",
    dataType: "boolean",
    required: false,
    filterable: true,
    publicationGroup: "specifications",
    displayOrder: 11,
  },
  "real_estate.charges_included": {
    id: "real_estate.charges_included",
    code: "charges_included",
    label: "Charges comprises",
    dataType: "boolean",
    required: false,
    publicationGroup: "legal",
    displayOrder: 12,
  },

  // ==========================================
  // EMPLOYMENT & JOBS
  // ==========================================
  "job.contract_type": {
    id: "job.contract_type",
    code: "contract_type",
    label: "Type de contrat",
    dataType: "select",
    required: true,
    filterable: true,
    publicationGroup: "general",
    displayOrder: 1,
    options: [
      { value: "cdi", label: "CDI" },
      { value: "cdd", label: "CDD" },
      { value: "interim", label: "Intérim" },
      { value: "alternance", label: "Alternance / Apprentissage" },
      { value: "stage", label: "Stage" },
      { value: "freelance", label: "Freelance / Indépendant" },
      { value: "saisonnier", label: "Saisonnier" },
      { value: "temps_partiel", label: "Temps partiel" },
      { value: "job_etudiant", label: "Job étudiant" },
    ],
  },
  "job.sector": {
    id: "job.sector",
    code: "job_sector",
    label: "Secteur d'activité",
    dataType: "select",
    required: true,
    filterable: true,
    publicationGroup: "general",
    displayOrder: 2,
    options: [
      { value: "tech_informatique", label: "Informatique / Tech / Data & IA" },
      { value: "commerce_vente", label: "Commerce & Vente" },
      { value: "marketing_com", label: "Marketing & Communication" },
      { value: "ingenierie_industrie", label: "Ingénierie & Industrie" },
      { value: "btp_construction", label: "BTP & Construction" },
      { value: "transport_logistique", label: "Transport & Logistique" },
      { value: "sante_social", label: "Santé & Social" },
      { value: "hotellerie_restauration", label: "Hôtellerie & Restauration" },
      {
        value: "finance_comptabilite",
        label: "Finance, Comptabilité & Juridique",
      },
      { value: "rh_recrutement", label: "Ressources Humaines" },
      { value: "education_formation", label: "Éducation & Formation" },
      { value: "artisanat_services", label: "Artisanat & Services" },
    ],
  },
  "job.experience_level": {
    id: "job.experience_level",
    code: "experience_level",
    label: "Niveau d'expérience requis",
    dataType: "select",
    required: false,
    filterable: true,
    publicationGroup: "specifications",
    displayOrder: 3,
    options: [
      { value: "debutant", label: "Débutant accepté (0-1 an)" },
      { value: "intermediaire", label: "Intermédiaire (2-4 ans)" },
      { value: "confirme", label: "Confirmé (5-8 ans)" },
      { value: "senior", label: "Senior / Expert (+8 ans)" },
    ],
  },
  "job.telework": {
    id: "job.telework",
    code: "telework",
    label: "Télétravail",
    dataType: "select",
    required: false,
    filterable: true,
    publicationGroup: "specifications",
    displayOrder: 4,
    options: [
      { value: "full", label: "Télétravail total (Full remote)" },
      { value: "hybrid", label: "Télétravail hybride (2-3 jours/semaine)" },
      { value: "occasional", label: "Télétravail ponctuel" },
      { value: "none", label: "Sur site uniquement" },
    ],
  },
  "job.salary_annual_keur": {
    id: "job.salary_annual_keur",
    code: "salary_annual_keur",
    label: "Rémunération annuelle brute",
    dataType: "number",
    unit: "k€/an",
    required: false,
    filterable: true,
    sortable: true,
    publicationGroup: "general",
    displayOrder: 5,
    validation: { min: 10, max: 300 },
  },

  // ==========================================
  // SERVICES
  // ==========================================
  "service.billing_mode": {
    id: "service.billing_mode",
    code: "billing_mode",
    label: "Mode de tarification",
    dataType: "select",
    required: true,
    filterable: true,
    publicationGroup: "general",
    displayOrder: 1,
    options: [
      { value: "hourly", label: "À l'heure" },
      { value: "flat_rate", label: "Au forfait" },
      { value: "quote", label: "Sur devis personnalisé" },
      { value: "free_first", label: "1er cours / bilan offert" },
    ],
  },
  "service.location_mode": {
    id: "service.location_mode",
    code: "location_mode",
    label: "Lieu de la prestation",
    dataType: "select",
    required: true,
    filterable: true,
    publicationGroup: "general",
    displayOrder: 2,
    options: [
      { value: "client_home", label: "À domicile (chez le client)" },
      { value: "provider_premises", label: "Dans les locaux du prestataire" },
      { value: "remote", label: "À distance (visio / en ligne)" },
      { value: "flexible", label: "Flexible / Selon besoin" },
    ],
  },
  "service.pro_decennale_insurance": {
    id: "service.pro_decennale_insurance",
    code: "pro_decennale_insurance",
    label: "Garantie décennale & RC Pro à jour",
    dataType: "boolean",
    required: false,
    filterable: true,
    publicationGroup: "legal",
    displayOrder: 3,
  },

  // ==========================================
  // TECH, SMARTPHONES & COMPUTING
  // ==========================================
  "tech.brand": {
    id: "tech.brand",
    code: "tech_brand",
    label: "Marque",
    dataType: "select",
    required: true,
    filterable: true,
    searchable: true,
    publicationGroup: "general",
    displayOrder: 1,
    options: [
      { value: "apple", label: "Apple" },
      { value: "samsung", label: "Samsung" },
      { value: "google", label: "Google Pixel" },
      { value: "xiaomi", label: "Xiaomi" },
      { value: "sony", label: "Sony" },
      { value: "lenovo", label: "Lenovo" },
      { value: "dell", label: "Dell" },
      { value: "hp", label: "HP" },
      { value: "asus", label: "Asus" },
      { value: "acer", label: "Acer" },
      { value: "msi", label: "MSI" },
      { value: "huawei", label: "Huawei" },
      { value: "oneplus", label: "OnePlus" },
      { value: "nintendo", label: "Nintendo" },
      { value: "microsoft", label: "Microsoft" },
      { value: "lg", label: "LG" },
      { value: "autre", label: "Autre marque" },
    ],
  },
  "tech.storage_capacity": {
    id: "tech.storage_capacity",
    code: "storage_capacity",
    label: "Capacité de stockage",
    dataType: "select",
    required: false,
    filterable: true,
    publicationGroup: "specifications",
    displayOrder: 2,
    options: [
      { value: "32_go", label: "32 Go" },
      { value: "64_go", label: "64 Go" },
      { value: "128_go", label: "128 Go" },
      { value: "256_go", label: "256 Go" },
      { value: "512_go", label: "512 Go" },
      { value: "1_to", label: "1 To (1000 Go)" },
      { value: "2_to", label: "2 To" },
      { value: "4_to_plus", label: "4 To ou plus" },
    ],
  },
  "tech.ram_memory": {
    id: "tech.ram_memory",
    code: "ram_memory",
    label: "Mémoire vive (RAM)",
    dataType: "select",
    required: false,
    filterable: true,
    publicationGroup: "specifications",
    displayOrder: 3,
    options: [
      { value: "4_go", label: "4 Go" },
      { value: "8_go", label: "8 Go" },
      { value: "16_go", label: "16 Go" },
      { value: "32_go", label: "32 Go" },
      { value: "64_go_plus", label: "64 Go ou plus" },
    ],
  },
  "tech.screen_size_inches": {
    id: "tech.screen_size_inches",
    code: "screen_size_inches",
    label: "Taille d'écran",
    dataType: "number",
    unit: "pouces",
    required: false,
    filterable: true,
    publicationGroup: "specifications",
    displayOrder: 4,
    validation: { min: 1, max: 120, step: 0.1 },
  },
  "tech.battery_health_percent": {
    id: "tech.battery_health_percent",
    code: "battery_health_percent",
    label: "État de la batterie",
    dataType: "number",
    unit: "%",
    required: false,
    filterable: true,
    publicationGroup: "performance",
    displayOrder: 5,
    validation: { min: 50, max: 100 },
  },
  "tech.gpu_model": {
    id: "tech.gpu_model",
    code: "gpu_model",
    label: "Carte graphique (GPU)",
    dataType: "text",
    required: false,
    filterable: true,
    searchable: true,
    publicationGroup: "specifications",
    displayOrder: 6,
    validation: { placeholder: "ex: RTX 4070, RX 7800 XT, M3 Pro" },
  },

  // ==========================================
  // FASHION / MODE
  // ==========================================
  "fashion.gender": {
    id: "fashion.gender",
    code: "gender",
    label: "Rayon / Genre",
    dataType: "select",
    required: true,
    filterable: true,
    publicationGroup: "general",
    displayOrder: 1,
    options: [
      { value: "femme", label: "Femme" },
      { value: "homme", label: "Homme" },
      { value: "fille", label: "Fille (Enfant)" },
      { value: "garcon", label: "Garçon (Enfant)" },
      { value: "bebe", label: "Bébé (0-36 mois)" },
      { value: "unisexe", label: "Unisexe" },
    ],
  },
  "fashion.clothing_size": {
    id: "fashion.clothing_size",
    code: "clothing_size",
    label: "Taille vêtement",
    dataType: "select",
    required: false,
    filterable: true,
    publicationGroup: "specifications",
    displayOrder: 2,
    options: [
      { value: "xxs", label: "XXS / 32" },
      { value: "xs", label: "XS / 34" },
      { value: "s", label: "S / 36" },
      { value: "m", label: "M / 38" },
      { value: "l", label: "L / 40" },
      { value: "xl", label: "XL / 42" },
      { value: "xxl", label: "XXL / 44" },
      { value: "xxxl", label: "XXXL / 46+" },
      { value: "taille_unique", label: "Taille unique" },
    ],
  },
  "fashion.shoe_size": {
    id: "fashion.shoe_size",
    code: "shoe_size",
    label: "Pointure",
    dataType: "select",
    required: false,
    filterable: true,
    publicationGroup: "specifications",
    displayOrder: 3,
    options: [
      { value: "35", label: "35" },
      { value: "36", label: "36" },
      { value: "37", label: "37" },
      { value: "38", label: "38" },
      { value: "39", label: "39" },
      { value: "40", label: "40" },
      { value: "41", label: "41" },
      { value: "42", label: "42" },
      { value: "43", label: "43" },
      { value: "44", label: "44" },
      { value: "45", label: "45" },
      { value: "46", label: "46" },
      { value: "47", label: "47+" },
    ],
  },

  // ==========================================
  // ENERGY & TRANSITION
  // ==========================================
  "energy.power_watts": {
    id: "energy.power_watts",
    code: "power_watts",
    label: "Puissance nominale",
    dataType: "number",
    unit: "W",
    required: false,
    filterable: true,
    publicationGroup: "performance",
    displayOrder: 1,
    validation: { min: 10, max: 100000 },
  },
  "energy.battery_capacity_kwh": {
    id: "energy.battery_capacity_kwh",
    code: "battery_capacity_kwh",
    label: "Capacité de stockage",
    dataType: "number",
    unit: "kWh",
    required: false,
    filterable: true,
    publicationGroup: "performance",
    displayOrder: 2,
    validation: { min: 0.5, max: 100 },
  },

  // ==========================================
  // PROFESSIONAL & BTP
  // ==========================================
  "pro.operating_hours": {
    id: "pro.operating_hours",
    code: "operating_hours",
    label: "Heures d'utilisation",
    dataType: "number",
    unit: "heures",
    required: false,
    filterable: true,
    publicationGroup: "specifications",
    displayOrder: 1,
    validation: { min: 0, max: 50000 },
  },
  "pro.tonnage_t": {
    id: "pro.tonnage_t",
    code: "tonnage_t",
    label: "Tonnage / Poids en ordre de marche",
    dataType: "number",
    unit: "tonnes",
    required: false,
    filterable: true,
    publicationGroup: "dimensions",
    displayOrder: 2,
    validation: { min: 0.5, max: 200 },
  },
  "pro.ce_certified": {
    id: "pro.ce_certified",
    code: "ce_certified",
    label: "Marquage CE & Certificat de conformité",
    dataType: "boolean",
    required: false,
    filterable: true,
    publicationGroup: "legal",
    displayOrder: 3,
  },
};
