import type { ComplianceRule } from "@shongre/contracts/compliance";

/** Deterministic projection of the server-owned registry for standalone demo mode. */
export const DEMO_COMPLIANCE_RULES: ComplianceRule[] = [
  {
    id: "global-browse-v1",
    jurisdiction: "*",
    regulation: "PRODUCT_BASELINE",
    ruleCode: "BROWSE_WITHOUT_IDENTIFICATION",
    description:
      "La consultation publique ne déclenche aucune vérification d’identité.",
    action: "browse",
    conditions: {},
    requiredChecks: [],
    recommendedChecks: [],
    reasonCodes: [],
    legalBasis: ["GDPR_DATA_MINIMISATION"],
    sourceReferences: ["https://eur-lex.europa.eu/eli/reg/2016/679/oj"],
    policyVersion: "baseline-2026.1",
    governance: "LEGAL_MANDATE",
    status: "ACTIVE",
    effectiveFrom: "2024-02-17T00:00:00.000Z",
    priority: 100,
    reviewedBy: "00000000-0000-4000-8000-000000000001",
    reviewedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "fr-private-listing-v1",
    jurisdiction: "FR",
    regulation: "MARKETPLACE_PUBLICATION",
    ruleCode: "PRIVATE_ORDINARY_LISTING",
    description:
      "Une annonce ordinaire de particulier demande seulement un compte confirmé.",
    action: "publish_listing",
    conditions: { accountTypes: ["individual"], sellerTypes: ["individual"] },
    requiredChecks: ["email", "professional_status"],
    recommendedChecks: ["phone"],
    reasonCodes: ["SELLER_CLASSIFICATION_REQUIRED"],
    legalBasis: ["CONTRACT", "LEGITIMATE_INTEREST_MARKETPLACE_SAFETY"],
    sourceReferences: [],
    policyVersion: "fr-2026.1",
    governance: "BUSINESS_POLICY",
    status: "ACTIVE",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    priority: 60,
  },
  {
    id: "fr-professional-listing-v1",
    jurisdiction: "FR",
    regulation: "TRADER_TRACEABILITY",
    ruleCode: "PROFESSIONAL_PUBLICATION_BASELINE",
    description:
      "La publication professionnelle vérifie l’entreprise et le représentant.",
    action: "publish_professional_listing",
    conditions: {
      accountTypes: ["professional"],
      sellerTypes: ["professional"],
    },
    requiredChecks: [
      "email",
      "business",
      "business_representative",
      "professional_status",
    ],
    recommendedChecks: ["phone", "vat"],
    reasonCodes: ["PROFESSIONAL_SELLER_TRACEABILITY"],
    legalBasis: ["DSA_ARTICLE_30_WHERE_APPLICABLE"],
    sourceReferences: ["https://eur-lex.europa.eu/eli/reg/2022/2065/oj"],
    policyVersion: "fr-dsa-2026.1",
    governance: "LEGAL_MANDATE",
    status: "ACTIVE",
    effectiveFrom: "2024-02-17T00:00:00.000Z",
    priority: 80,
    reviewedBy: "00000000-0000-4000-8000-000000000001",
    reviewedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "fr-payout-individual-v1",
    jurisdiction: "FR",
    regulation: "PAYMENT_SERVICES",
    ruleCode: "PSP_PAYOUT_INDIVIDUAL",
    description: "Seul le versement reste bloqué pendant les contrôles du PSP.",
    action: "receive_payout",
    conditions: {
      sellerTypes: ["individual"],
      paymentFlows: ["psp_marketplace"],
    },
    requiredChecks: ["email", "identity", "bank_account", "payout"],
    recommendedChecks: ["phone"],
    reasonCodes: ["PAYOUT_PROVIDER_REQUIREMENTS"],
    legalBasis: ["PSP_REGULATORY_REQUIREMENTS"],
    sourceReferences: [
      "https://acpr.banque-france.fr/fr/professionnels/lacpr-vous-accompagne/parcours-fintech/contenus-pedagogiques/de-quel-statut-releve-mon-activite/jencaisse-des-fonds-et-les-reverse-une-tierce-personne",
    ],
    policyVersion: "payments-2026.1",
    governance: "LEGAL_MANDATE",
    status: "ACTIVE",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    priority: 100,
    reviewedBy: "00000000-0000-4000-8000-000000000001",
    reviewedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "fr-dac7-due-diligence-review-v1",
    jurisdiction: "FR",
    regulation: "DAC7_DPI",
    ruleCode: "FACILITATED_ACTIVITY_DUE_DILIGENCE",
    description:
      "La diligence fiscale attend la qualification juridique exacte de l’activité.",
    action: "complete_tax_due_diligence",
    conditions: {
      transactionTypes: ["direct_purchase", "service_booking", "reservation"],
      contractConclusionModes: ["platform", "unknown"],
    },
    requiredChecks: [],
    recommendedChecks: ["tax", "address"],
    reasonCodes: ["DAC7_APPLICABILITY_MUST_BE_CONFIRMED"],
    legalBasis: ["DAC7_DPI_WHERE_APPLICABLE"],
    sourceReferences: ["https://eur-lex.europa.eu/eli/dir/2021/514/oj"],
    policyVersion: "fr-dac7-2026.1",
    governance: "LEGAL_MANDATE",
    status: "LEGAL_REVIEW_REQUIRED",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    priority: 100,
  },
];
