import type { SolutionDefinition } from "../../../domains/solutions/solutions.types";

const CREATED_AT = "2026-05-15T09:00:00.000Z";
const UPDATED_AT = "2026-08-15T10:15:00.000Z";

export const DEMO_SOLUTIONS: readonly SolutionDefinition[] = [
  {
    id: "solution-prospects",
    name: "Shongre Prospects",
    slug: "prospects",
    shortDescription:
      "Trouvez et qualifiez des prospects B2B pertinents pour alimenter votre développement commercial.",
    description:
      "Transformez un profil cible en entreprises qualifiées avec des preuves sourcées, un score expliqué et une validation humaine.",
    icon: "prospects",
    category: "Développement commercial",
    lifecycle: "AVAILABLE",
    availableFrom: "2026-06-01T00:00:00.000Z",
    markets: ["FR", "BE", "LU"],
    languages: ["fr-FR", "fr-BE"],
    audiences: ["Organisations professionnelles", "Équipes commerciales"],
    capabilities: [
      "Définir un profil cible",
      "Découvrir des entreprises pertinentes",
      "Qualifier avec des preuves",
      "Partager les actions avec l’équipe",
    ],
    launchApplicationId: "prospects",
    launchPath: "/",
    entitlementKey: "solution.prospects.access",
    requiresAuthentication: false,
    requiresEntitlement: false,
    releaseNotes: [
      {
        id: "prospects-2026-08",
        title: "Qualification explicable",
        body: "Les preuves et informations manquantes sont regroupées dans le dossier prospect.",
        publishedAt: UPDATED_AT,
      },
    ],
    sortOrder: 10,
    catalogVisible: true,
    featured: true,
    createdAt: CREATED_AT,
    updatedAt: UPDATED_AT,
  },
  {
    id: "solution-facturation",
    name: "Shongre Facturation",
    slug: "facturation",
    shortDescription:
      "Créez des factures conformes et suivez vos paiements en toute simplicité.",
    description:
      "Créez des factures conformes et suivez vos paiements, sans quitter votre organisation Shongre.",
    icon: "facturation",
    category: "Gestion financière",
    lifecycle: "BETA",
    availableFrom: "2026-08-15T00:00:00.000Z",
    markets: ["FR", "BE", "LU"],
    languages: ["fr-FR", "fr-BE"],
    audiences: ["Organisations professionnelles", "Comptables"],
    capabilities: [
      "Configurer votre organisation",
      "Gérer vos clients",
      "Créer et finaliser vos factures",
      "Suivre les paiements",
    ],
    launchApplicationId: "facturation",
    launchPath: "/",
    entitlementKey: "solution.facturation.access",
    requiresAuthentication: false,
    requiresEntitlement: false,
    releaseNotes: [
      {
        id: "facturation-2026-08",
        title: "Parcours de facturation multi-marché",
        body: "Création, finalisation, export et suivi sont disponibles dans la démonstration.",
        publishedAt: UPDATED_AT,
      },
    ],
    notice:
      "Cette solution est en version bêta. Les fonctionnalités évoluent régulièrement sans bloquer le parcours de facturation pris en charge.",
    sortOrder: 20,
    catalogVisible: true,
    featured: true,
    createdAt: CREATED_AT,
    updatedAt: UPDATED_AT,
  },
  {
    id: "solution-pilotage",
    name: "Shongre Pilotage",
    slug: "pilotage",
    shortDescription:
      "Suivez vos indicateurs clés avec des tableaux de bord partagés.",
    description:
      "Réunissez les indicateurs utiles à votre organisation dans un espace de pilotage commun.",
    icon: "pilotage",
    category: "Pilotage",
    lifecycle: "COMING_SOON",
    markets: ["FR", "BE", "LU"],
    languages: ["fr-FR"],
    audiences: ["Dirigeants", "Responsables d’équipe"],
    capabilities: [
      "Partager les indicateurs",
      "Suivre les échéances",
      "Comparer les périodes",
    ],
    requiresAuthentication: false,
    requiresEntitlement: false,
    releaseNotes: [],
    sortOrder: 40,
    catalogVisible: true,
    featured: false,
    createdAt: CREATED_AT,
    updatedAt: UPDATED_AT,
  },
  {
    id: "solution-marketplace",
    name: "Shongre Marketplace",
    slug: "marketplace",
    shortDescription:
      "Achetez, vendez et développez votre activité sur la place de marché Shongre.",
    description:
      "Publiez, recherchez et échangez sur la place de marché multi-pays de Shongre, pour particuliers et professionnels.",
    icon: "marketplace",
    category: "Commerce",
    lifecycle: "AVAILABLE",
    availableFrom: "2026-01-01T00:00:00.000Z",
    markets: ["FR", "BE", "LU"],
    languages: ["fr-FR", "fr-BE"],
    audiences: ["Particuliers", "Organisations professionnelles"],
    capabilities: [
      "Rechercher des annonces",
      "Publier dans plusieurs marchés",
      "Échanger avec acheteurs et vendeurs",
      "Gérer annonces, favoris et messages",
    ],
    launchApplicationId: "marketplace",
    launchPath: "/",
    requiresAuthentication: false,
    requiresEntitlement: false,
    releaseNotes: [
      {
        id: "marketplace-2026-08",
        title: "Parcours multi-marché",
        body: "La sélection du marché et les destinations canoniques restent cohérentes sur les principaux parcours.",
        publishedAt: UPDATED_AT,
      },
    ],
    sortOrder: 30,
    catalogVisible: true,
    featured: false,
    createdAt: CREATED_AT,
    updatedAt: UPDATED_AT,
  },
  {
    id: "solution-reservations",
    name: "Shongre Réservations",
    slug: "reservations",
    shortDescription: "Planifiez les rendez-vous de votre organisation.",
    description: "Brouillon de produit conservé pour la démonstration admin.",
    icon: "apps",
    category: "Organisation",
    lifecycle: "DRAFT",
    markets: ["FR"],
    languages: ["fr-FR"],
    audiences: ["Organisations professionnelles"],
    capabilities: ["Planifier un rendez-vous"],
    entitlementKey: "solution.reservations.access",
    requiresAuthentication: true,
    requiresEntitlement: true,
    releaseNotes: [],
    sortOrder: 40,
    catalogVisible: false,
    featured: false,
    createdAt: CREATED_AT,
    updatedAt: UPDATED_AT,
  },
  {
    id: "solution-ancien-pro",
    name: "Shongre Ancien Pro",
    slug: "ancien-pro",
    shortDescription: "Ancien espace professionnel Shongre.",
    description: "Produit retiré, conservé dans l’historique de gouvernance.",
    icon: "apps",
    category: "Historique",
    lifecycle: "RETIRED",
    markets: ["FR"],
    languages: ["fr-FR"],
    audiences: ["Organisations professionnelles"],
    capabilities: [],
    entitlementKey: "solution.ancien-pro.access",
    requiresAuthentication: true,
    requiresEntitlement: true,
    releaseNotes: [],
    notice: "Ce produit a été retiré du catalogue public.",
    sortOrder: 90,
    catalogVisible: false,
    featured: false,
    createdAt: CREATED_AT,
    updatedAt: UPDATED_AT,
  },
] as const;
