/** GENERATED by scripts/sync-brand-assets.ts. Do not edit manually. */
import type { ImageSourcePropType } from "react-native";

export const mobileBrandImages = {
  primary: require("../assets/brand/logo/horizontal-primary.png"),
  reverse: require("../assets/brand/logo/horizontal-reverse.png"),
} satisfies Record<"primary" | "reverse", ImageSourcePropType>;
