/** GENERATED by scripts/sync-brand-assets.ts from brand/shongre/brand.config.json. Do not edit manually. */
export const activeBrand = {
  signature: "SHONGRE.",
  version: "1.2.0",
  cacheKey: "shongre-1.2.0",
} as const;

export type ActiveBrand = typeof activeBrand;
