/** GENERATED by scripts/sync-brand-assets.ts from the active SHONGRE. asset mapping. Do not edit manually. */
export const webBrandAssets = {
  version: "1.1.0",
  cacheKey: "shongre-1.1.0",
  manifest: "/manifest.webmanifest",
  favicon: {
    ico: {
      src: "/favicon.ico?brand=1.1.0",
      type: "image/x-icon",
    },
    png: [
      {
        src: "/favicon-16x16.png?brand=1.1.0",
        type: "image/png",
        sizes: "16x16",
      },
      {
        src: "/favicon-32x32.png?brand=1.1.0",
        type: "image/png",
        sizes: "32x32",
      },
      {
        src: "/favicon-48x48.png?brand=1.1.0",
        type: "image/png",
        sizes: "48x48",
      },
      {
        src: "/favicon-64x64.png?brand=1.1.0",
        type: "image/png",
        sizes: "64x64",
      },
      {
        src: "/favicon-96x96.png?brand=1.1.0",
        type: "image/png",
        sizes: "96x96",
      },
    ],
    appleTouch: {
      src: "/apple-touch-icon.png?brand=1.1.0",
      type: "image/png",
      sizes: "180x180",
    },
  },
  logo: {
    horizontal: {
      primary: {
        src: "/brand/shongre/logo/header-primary-480.png?brand=1.1.0",
        width: 480,
        height: 123,
        srcSet:
          "/brand/shongre/logo/header-primary-240.png?brand=1.1.0 240w, /brand/shongre/logo/header-primary-480.png?brand=1.1.0 480w, /brand/shongre/logo/header-primary-960.png?brand=1.1.0 960w",
      },
      reverse: {
        src: "/brand/shongre/logo/header-reverse-480.png?brand=1.1.0",
        width: 480,
        height: 123,
        srcSet:
          "/brand/shongre/logo/header-reverse-240.png?brand=1.1.0 240w, /brand/shongre/logo/header-reverse-480.png?brand=1.1.0 480w, /brand/shongre/logo/header-reverse-960.png?brand=1.1.0 960w",
      },
      "mono-ink": {
        src: "/brand/shongre/logo/horizontal-mono-ink.png?brand=1.1.0",
        width: 1956,
        height: 500,
      },
      "mono-white": {
        src: "/brand/shongre/logo/horizontal-mono-white.png?brand=1.1.0",
        width: 1956,
        height: 500,
      },
      "mono-orange": {
        src: "/brand/shongre/logo/horizontal-mono-orange.png?brand=1.1.0",
        width: 1956,
        height: 500,
      },
    },
    stacked: {
      primary: {
        src: "/brand/shongre/logo/stacked-primary.svg?brand=1.1.0",
        width: 1197,
        height: 843,
      },
      "mono-ink": {
        src: "/brand/shongre/logo/stacked-mono-ink.png?brand=1.1.0",
        width: 1197,
        height: 843,
      },
      "mono-white": {
        src: "/brand/shongre/logo/stacked-mono-white.png?brand=1.1.0",
        width: 1197,
        height: 843,
      },
    },
    wordmark: {
      primary: {
        src: "/brand/shongre/logo/wordmark-primary.svg?brand=1.1.0",
        width: 2024,
        height: 383,
      },
      reverse: {
        src: "/brand/shongre/logo/wordmark-reverse.png?brand=1.1.0",
        width: 2024,
        height: 383,
      },
      "mono-ink": {
        src: "/brand/shongre/logo/wordmark-mono-ink.png?brand=1.1.0",
        width: 2024,
        height: 383,
      },
      "mono-white": {
        src: "/brand/shongre/logo/wordmark-mono-white.png?brand=1.1.0",
        width: 2024,
        height: 383,
      },
    },
    header: {
      primary240: {
        src: "/brand/shongre/logo/header-primary-240.png?brand=1.1.0",
        width: 240,
        height: 61,
      },
      primary480: {
        src: "/brand/shongre/logo/header-primary-480.png?brand=1.1.0",
        width: 480,
        height: 123,
      },
      primary960: {
        src: "/brand/shongre/logo/header-primary-960.png?brand=1.1.0",
        width: 960,
        height: 245,
      },
      reverse240: {
        src: "/brand/shongre/logo/header-reverse-240.png?brand=1.1.0",
        width: 240,
        height: 61,
      },
      reverse480: {
        src: "/brand/shongre/logo/header-reverse-480.png?brand=1.1.0",
        width: 480,
        height: 123,
      },
      reverse960: {
        src: "/brand/shongre/logo/header-reverse-960.png?brand=1.1.0",
        width: 960,
        height: 245,
      },
    },
  },
  icon: {
    primary: {
      src: "/brand/shongre/pwa/icon-maskable-192.png?brand=1.1.0",
      width: 192,
      height: 192,
    },
    structuredData: {
      src: "/brand/shongre/icon/primary.svg?brand=1.1.0",
      width: 1106,
      height: 1082,
    },
    "mono-ink": {
      src: "/brand/shongre/icon/mono-ink.svg?brand=1.1.0",
      width: 1106,
      height: 1082,
    },
    "mono-white": {
      src: "/brand/shongre/icon/mono-white.svg?brand=1.1.0",
      width: 1106,
      height: 1082,
    },
    "mono-orange": {
      src: "/brand/shongre/icon/mono-orange.png?brand=1.1.0",
      width: 1106,
      height: 1082,
    },
  },
  pwa: {
    icons: [
      {
        src: "/brand/shongre/pwa/icon-192.png?brand=1.1.0",
        width: 192,
        height: 192,
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/brand/shongre/pwa/icon-512.png?brand=1.1.0",
        width: 512,
        height: 512,
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/brand/shongre/pwa/icon-maskable-192.png?brand=1.1.0",
        width: 192,
        height: 192,
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/brand/shongre/pwa/icon-maskable-512.png?brand=1.1.0",
        width: 512,
        height: 512,
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  },
  social: {
    openGraphLight: {
      src: "/brand/shongre/social/open-graph-light.png?brand=1.1.0",
      width: 1200,
      height: 630,
    },
    openGraphDark: {
      src: "/brand/shongre/social/open-graph-dark.png?brand=1.1.0",
      width: 1200,
      height: 630,
    },
  },
} as const;
