-- Canonical customer-support domain. Support is operational work with its own
-- least-privilege queue, SLA evidence and audit history; it is not a generic
-- administrator view over arbitrary user tables.

CREATE TABLE IF NOT EXISTS public.support_sla_policies (
  category TEXT NOT NULL CHECK (category IN (
    'account','listing','payment','subscription','verification','safety',
    'privacy','technical','other'
  )),
  priority TEXT NOT NULL CHECK (priority IN ('low','normal','high','urgent')),
  first_response_minutes INTEGER NOT NULL CHECK (first_response_minutes > 0),
  resolution_minutes INTEGER NOT NULL CHECK (resolution_minutes > 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  updated_by UUID REFERENCES public.profiles(id) ON DELETE RESTRICT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (category, priority)
);

INSERT INTO public.support_sla_policies
  (category, priority, first_response_minutes, resolution_minutes)
SELECT category, priority,
  CASE priority
    WHEN 'urgent' THEN 30
    WHEN 'high' THEN 120
    WHEN 'normal' THEN 480
    ELSE 1440
  END,
  CASE priority
    WHEN 'urgent' THEN 240
    WHEN 'high' THEN 720
    WHEN 'normal' THEN 2880
    ELSE 4320
  END
FROM unnest(ARRAY[
  'account','listing','payment','subscription','verification','safety',
  'privacy','technical','other'
]) AS category
CROSS JOIN unnest(ARRAY['low','normal','high','urgent']) AS priority
ON CONFLICT (category, priority) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.support_cases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_number BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  requester_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  assignee_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  category TEXT NOT NULL CHECK (category IN (
    'account','listing','payment','subscription','verification','safety',
    'privacy','technical','other'
  )),
  priority TEXT NOT NULL CHECK (priority IN ('low','normal','high','urgent')),
  status TEXT NOT NULL CHECK (status IN (
    'open','assigned','waiting_customer','waiting_internal','resolved','closed'
  )),
  subject TEXT NOT NULL CHECK (char_length(subject) BETWEEN 5 AND 160),
  description TEXT NOT NULL CHECK (char_length(description) BETWEEN 20 AND 10000),
  listing_id UUID REFERENCES public.listings(id) ON DELETE SET NULL,
  order_id UUID REFERENCES public.orders(id) ON DELETE SET NULL,
  payment_id TEXT,
  organization_id UUID REFERENCES public.organizations(id) ON DELETE SET NULL,
  sla_first_response_due_at TIMESTAMPTZ,
  sla_resolution_due_at TIMESTAMPTZ NOT NULL,
  first_response_at TIMESTAMPTZ,
  last_customer_reply_at TIMESTAMPTZ,
  last_staff_reply_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  closed_at TIMESTAMPTZ,
  satisfaction_score SMALLINT CHECK (satisfaction_score BETWEEN 1 AND 5),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (resolved_at IS NULL OR status IN ('resolved','closed')),
  CHECK (closed_at IS NULL OR status = 'closed')
);
CREATE INDEX IF NOT EXISTS support_cases_requester_idx
  ON public.support_cases (requester_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS support_cases_queue_idx
  ON public.support_cases (status, priority, sla_resolution_due_at)
  WHERE status NOT IN ('resolved','closed');
CREATE INDEX IF NOT EXISTS support_cases_assignee_idx
  ON public.support_cases (assignee_id, status, updated_at DESC)
  WHERE assignee_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS support_cases_listing_idx
  ON public.support_cases (listing_id) WHERE listing_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS support_cases_order_idx
  ON public.support_cases (order_id) WHERE order_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS support_cases_organization_idx
  ON public.support_cases (organization_id) WHERE organization_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.support_case_notes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID NOT NULL REFERENCES public.support_cases(id) ON DELETE CASCADE,
  author_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  visibility TEXT NOT NULL CHECK (visibility IN ('customer','internal')),
  body TEXT NOT NULL CHECK (char_length(body) BETWEEN 2 AND 10000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS support_case_notes_case_idx
  ON public.support_case_notes (case_id, created_at);

CREATE TABLE IF NOT EXISTS public.support_case_attachments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID NOT NULL REFERENCES public.support_cases(id) ON DELETE CASCADE,
  note_id UUID REFERENCES public.support_case_notes(id) ON DELETE CASCADE,
  uploaded_by UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  private_document_asset_id UUID NOT NULL
    REFERENCES public.private_document_assets(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (note_id IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS support_case_attachments_case_idx
  ON public.support_case_attachments (case_id, created_at);

CREATE TABLE IF NOT EXISTS public.support_case_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID NOT NULL REFERENCES public.support_cases(id) ON DELETE RESTRICT,
  actor_id UUID REFERENCES public.profiles(id) ON DELETE RESTRICT,
  event_type TEXT NOT NULL,
  reason TEXT NOT NULL CHECK (char_length(reason) BETWEEN 10 AND 2000),
  previous_value JSONB,
  new_value JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS support_case_events_case_idx
  ON public.support_case_events (case_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.support_macros (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL CHECK (char_length(title) BETWEEN 2 AND 120),
  body TEXT NOT NULL CHECK (char_length(body) BETWEEN 2 AND 10000),
  category TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by UUID REFERENCES public.profiles(id) ON DELETE RESTRICT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION public.update_support_case(
  p_case_id UUID,
  p_actor_id UUID,
  p_status TEXT,
  p_priority TEXT,
  p_assignee_id UUID,
  p_last_customer_reply_at TIMESTAMPTZ,
  p_last_staff_reply_at TIMESTAMPTZ,
  p_reason TEXT
)
RETURNS SETOF public.support_cases
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  previous_case public.support_cases%ROWTYPE;
  updated_case public.support_cases%ROWTYPE;
BEGIN
  IF char_length(trim(p_reason)) < 10 THEN
    RAISE EXCEPTION 'A support case change reason is required'
      USING ERRCODE = '22023';
  END IF;

  SELECT * INTO previous_case
  FROM public.support_cases
  WHERE id = p_case_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Support case not found' USING ERRCODE = 'P0002';
  END IF;

  UPDATE public.support_cases
  SET status = p_status,
      priority = p_priority,
      assignee_id = p_assignee_id,
      last_customer_reply_at = p_last_customer_reply_at,
      last_staff_reply_at = p_last_staff_reply_at,
      first_response_at = CASE
        WHEN first_response_at IS NULL AND p_last_staff_reply_at IS NOT NULL
          THEN p_last_staff_reply_at
        ELSE first_response_at
      END,
      resolved_at = CASE
        WHEN p_status IN ('resolved','closed') THEN COALESCE(resolved_at, NOW())
        ELSE NULL
      END,
      closed_at = CASE WHEN p_status = 'closed' THEN COALESCE(closed_at, NOW()) ELSE NULL END,
      updated_at = NOW()
  WHERE id = p_case_id
  RETURNING * INTO updated_case;

  INSERT INTO public.support_case_events
    (case_id, actor_id, event_type, reason, previous_value, new_value)
  VALUES (
    p_case_id,
    p_actor_id,
    'case_updated',
    trim(p_reason),
    jsonb_build_object(
      'status', previous_case.status,
      'priority', previous_case.priority,
      'assigneeId', previous_case.assignee_id
    ),
    jsonb_build_object(
      'status', updated_case.status,
      'priority', updated_case.priority,
      'assigneeId', updated_case.assignee_id
    )
  );

  RETURN NEXT updated_case;
END;
$$;

CREATE OR REPLACE FUNCTION public.support_case_metrics(p_now TIMESTAMPTZ)
RETURNS TABLE (
  open_count BIGINT,
  urgent_count BIGINT,
  overdue_count BIGINT,
  unassigned_count BIGINT,
  resolved_today_count BIGINT,
  average_first_response_minutes NUMERIC
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT
    count(*) FILTER (WHERE status NOT IN ('resolved','closed')),
    count(*) FILTER (
      WHERE status NOT IN ('resolved','closed') AND priority = 'urgent'
    ),
    count(*) FILTER (
      WHERE status NOT IN ('resolved','closed') AND sla_resolution_due_at < p_now
    ),
    count(*) FILTER (
      WHERE status NOT IN ('resolved','closed') AND assignee_id IS NULL
    ),
    count(*) FILTER (
      WHERE resolved_at >= date_trunc('day', p_now)
        AND resolved_at < date_trunc('day', p_now) + INTERVAL '1 day'
    ),
    COALESCE(avg(extract(epoch FROM (first_response_at - created_at)) / 60), 0)
  FROM public.support_cases;
$$;

ALTER TABLE public.support_sla_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_case_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_case_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_case_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_macros ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.support_sla_policies FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.support_cases FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.support_case_notes FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.support_case_attachments FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.support_case_events FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.support_macros FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.support_sla_policies TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.support_cases TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.support_case_notes TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.support_case_attachments TO service_role;
GRANT SELECT, INSERT ON public.support_case_events TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.support_macros TO service_role;

REVOKE ALL ON FUNCTION public.update_support_case(
  UUID, UUID, TEXT, TEXT, UUID, TIMESTAMPTZ, TIMESTAMPTZ, TEXT
)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.support_case_metrics(TIMESTAMPTZ)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.update_support_case(
  UUID, UUID, TEXT, TEXT, UUID, TIMESTAMPTZ, TIMESTAMPTZ, TEXT
)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.support_case_metrics(TIMESTAMPTZ)
  TO service_role;
