import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { format } from "prettier";
import {
  BRAND_SIGNATURE,
  BRAND_VERSION,
  brandCacheKey,
  brandAssetMappings,
  brandConsumerAssets,
  brandMobileImageRegistryDestination,
  brandSourceRoot,
  repositoryRoot,
} from "./brand-assets.config";

export async function sha256(file: string): Promise<string> {
  return createHash("sha256")
    .update(await readFile(file))
    .digest("hex");
}

export async function readCanonicalChecksums(): Promise<Map<string, string>> {
  const contents = await readFile(
    path.join(brandSourceRoot, "CHECKSUMS.sha256"),
    "utf8",
  );
  const checksums = new Map<string, string>();
  for (const line of contents.split(/\r?\n/)) {
    if (!line.trim()) continue;
    const match = line.match(/^([a-f\d]{64})\s+\*?(.+)$/i);
    if (!match) throw new Error(`Invalid checksum entry: ${line}`);
    const relative = match[2].replaceAll("\\", "/");
    if (relative.startsWith("/") || relative.split("/").includes("..")) {
      throw new Error(`Unsafe checksum path: ${relative}`);
    }
    if (checksums.has(relative)) {
      throw new Error(`Duplicate checksum path: ${relative}`);
    }
    checksums.set(relative, match[1].toLowerCase());
  }
  return checksums;
}

export async function validateCanonicalChecksums(): Promise<void> {
  const checksums = await readCanonicalChecksums();
  for (const [relative, expected] of checksums) {
    const actual = await sha256(canonicalBrandPath(relative));
    if (actual !== expected) {
      throw new Error(
        `Brand source checksum mismatch for ${relative}: expected ${expected}, received ${actual}.`,
      );
    }
  }
}

interface CanonicalBrandTokens {
  brand: { signature: string; version: string };
  color: Record<string, { value: string; type: string }>;
}

export async function renderBrandTokenAdapter(source: string): Promise<string> {
  const tokens = JSON.parse(
    await readFile(canonicalBrandPath(source), "utf8"),
  ) as CanonicalBrandTokens;
  if (
    tokens.brand.signature !== BRAND_SIGNATURE ||
    tokens.brand.version !== BRAND_VERSION
  ) {
    throw new Error(
      `Brand token identity must be ${BRAND_SIGNATURE} v${BRAND_VERSION}.`,
    );
  }
  const required = ["orange", "ink", "white", "mist", "border", "muted"];
  for (const name of required) {
    if (!/^#[A-F\d]{6}$/i.test(tokens.color[name]?.value ?? "")) {
      throw new Error(`Brand token color.${name} is missing or invalid.`);
    }
  }
  return format(
    `/**\n * GENERATED by scripts/sync-brand-assets.ts from\n * brand/shongre/v${BRAND_VERSION}/${source}. Do not edit manually.\n */\nexport const brandPalette = ${JSON.stringify(
      Object.fromEntries(
        required.map((name) => [name, tokens.color[name].value.toUpperCase()]),
      ),
      null,
      2,
    )};\n`,
    { parser: "babel" },
  );
}

export async function renderBrandTokenTypes(source: string): Promise<string> {
  const adapter = await renderBrandTokenAdapter(source);
  const entries = [...adapter.matchAll(/^\s{2}(\w+):\s*"(#[A-F\d]{6})",?$/gim)];
  if (entries.length === 0) {
    throw new Error("Unable to derive brand token declarations.");
  }
  return format(
    `/** GENERATED by scripts/sync-brand-assets.ts. Do not edit manually. */\nexport declare const brandPalette: { ${entries
      .map(
        ([, name, value]) =>
          `readonly ${name}: ${JSON.stringify(value.toUpperCase())};`,
      )
      .join(" ")} };\n`,
    { parser: "typescript" },
  );
}

export async function renderBrandDocumentAdapter(
  source: string,
): Promise<string> {
  const encoded = (await readFile(canonicalBrandPath(source))).toString(
    "base64",
  );
  return format(
    `/**\n * GENERATED by scripts/sync-brand-assets.ts from\n * brand/shongre/v${BRAND_VERSION}/${source}. Do not edit manually.\n *\n * The data URI keeps downloaded HTML invoices self-contained.\n */\nexport const brandDocumentLogoDataUri = ${JSON.stringify(
      `data:image/png;base64,${encoded}`,
    )} as const;\n`,
    { parser: "typescript" },
  );
}

export async function renderBrandActiveRegistry(
  version = BRAND_VERSION,
): Promise<string> {
  const cacheKey = brandCacheKey(version);
  return format(
    `/** GENERATED by scripts/sync-brand-assets.ts from brand/shongre/brand.config.json. Do not edit manually. */\nexport const activeBrand = ${JSON.stringify(
      {
        signature: BRAND_SIGNATURE,
        version,
        cacheKey,
      },
      null,
      2,
    )} as const;\n\nexport type ActiveBrand = typeof activeBrand;\n`,
    { parser: "typescript" },
  );
}

function assertMappedDestination(
  destination: string,
  options: { directory?: boolean } = {},
): void {
  const matched = brandAssetMappings.some(({ destination: mapped }) =>
    options.directory
      ? mapped.startsWith(`${destination.replace(/\/$/, "")}/`)
      : mapped === destination,
  );
  if (!matched) {
    throw new Error(
      `Brand consumer registry points outside managed mappings: ${destination}`,
    );
  }
}

function webPublicPath(destination: string): string {
  assertMappedDestination(destination);
  const prefix = "frontend/public/";
  if (!destination.startsWith(prefix)) {
    throw new Error(`Web brand asset is not public: ${destination}`);
  }
  return `/${destination.slice(prefix.length)}`;
}

function versionedWebPublicPath(destination: string, version: string): string {
  return `${webPublicPath(destination)}?brand=${version}`;
}

function mobileProjectPath(
  destination: string,
  options: { directory?: boolean } = {},
): string {
  assertMappedDestination(destination, options);
  const prefix = "mobile/";
  if (!destination.startsWith(prefix)) {
    throw new Error(
      `Mobile brand asset is outside the Expo project: ${destination}`,
    );
  }
  return `./${destination.slice(prefix.length)}`;
}

export async function renderBrandWebRegistry(
  version = BRAND_VERSION,
): Promise<string> {
  const { web } = brandConsumerAssets;
  const [headerPrimary240, headerPrimary480, headerPrimary960] =
    web.logo.headerPrimary.map((destination) =>
      versionedWebPublicPath(destination, version),
    );
  const [headerReverse240, headerReverse480, headerReverse960] =
    web.logo.headerReverse.map((destination) =>
      versionedWebPublicPath(destination, version),
    );
  const asset = (destination: string, width: number, height: number) => ({
    src: versionedWebPublicPath(destination, version),
    width,
    height,
  });
  const registry = {
    version,
    cacheKey: brandCacheKey(version),
    manifest: "/manifest.webmanifest",
    favicon: {
      ico: {
        src: versionedWebPublicPath(web.favicon.ico, version),
        type: "image/x-icon",
      },
      png: web.favicon.png.map((destination, index) => {
        const size = [16, 32, 48, 64, 96][index];
        return {
          src: versionedWebPublicPath(destination, version),
          type: "image/png",
          sizes: `${size}x${size}`,
        };
      }),
      appleTouch: {
        src: versionedWebPublicPath(web.favicon.appleTouch, version),
        type: "image/png",
        sizes: "180x180",
      },
    },
    logo: {
      horizontal: {
        primary: {
          ...asset(web.logo.horizontal.primary, 480, 123),
          srcSet: `${headerPrimary240} 240w, ${headerPrimary480} 480w, ${headerPrimary960} 960w`,
        },
        reverse: {
          ...asset(web.logo.horizontal.reverse, 480, 123),
          srcSet: `${headerReverse240} 240w, ${headerReverse480} 480w, ${headerReverse960} 960w`,
        },
        "mono-ink": asset(web.logo.horizontal.monoInk, 1956, 500),
        "mono-white": asset(web.logo.horizontal.monoWhite, 1956, 500),
        "mono-orange": asset(web.logo.horizontal.monoOrange, 1956, 500),
      },
      stacked: {
        primary: asset(web.logo.stacked.primary, 1197, 843),
        "mono-ink": asset(web.logo.stacked.monoInk, 1197, 843),
        "mono-white": asset(web.logo.stacked.monoWhite, 1197, 843),
      },
      wordmark: {
        primary: asset(web.logo.wordmark.primary, 2024, 383),
        reverse: asset(web.logo.wordmark.reverse, 2024, 383),
        "mono-ink": asset(web.logo.wordmark.monoInk, 2024, 383),
        "mono-white": asset(web.logo.wordmark.monoWhite, 2024, 383),
      },
      header: {
        primary240: asset(web.logo.headerPrimary[0], 240, 61),
        primary480: asset(web.logo.headerPrimary[1], 480, 123),
        primary960: asset(web.logo.headerPrimary[2], 960, 245),
        reverse240: asset(web.logo.headerReverse[0], 240, 61),
        reverse480: asset(web.logo.headerReverse[1], 480, 123),
        reverse960: asset(web.logo.headerReverse[2], 960, 245),
      },
    },
    icon: {
      primary: asset(web.icon.primary, 192, 192),
      structuredData: asset(web.icon.structuredData, 1106, 1082),
      "mono-ink": asset(web.icon.monoInk, 1106, 1082),
      "mono-white": asset(web.icon.monoWhite, 1106, 1082),
      "mono-orange": asset(web.icon.monoOrange, 1106, 1082),
    },
    pwa: {
      icons: [
        {
          ...asset(web.pwa.any192, 192, 192),
          sizes: "192x192",
          type: "image/png",
          purpose: "any",
        },
        {
          ...asset(web.pwa.any512, 512, 512),
          sizes: "512x512",
          type: "image/png",
          purpose: "any",
        },
        {
          ...asset(web.pwa.maskable192, 192, 192),
          sizes: "192x192",
          type: "image/png",
          purpose: "maskable",
        },
        {
          ...asset(web.pwa.maskable512, 512, 512),
          sizes: "512x512",
          type: "image/png",
          purpose: "maskable",
        },
      ],
    },
    social: {
      openGraphLight: asset(web.social.openGraphLight, 1200, 630),
      openGraphDark: asset(web.social.openGraphDark, 1200, 630),
    },
  };

  return format(
    `/** GENERATED by scripts/sync-brand-assets.ts from the active SHONGRE. asset mapping. Do not edit manually. */\nexport const webBrandAssets = ${JSON.stringify(registry, null, 2)} as const;\n`,
    { parser: "typescript" },
  );
}

export function renderBrandMobileRegistry(version = BRAND_VERSION): string {
  const { mobile } = brandConsumerAssets;
  const registry = {
    notice: "GENERATED by scripts/sync-brand-assets.ts. Do not edit manually.",
    brandSignature: BRAND_SIGNATURE,
    brandVersion: version,
    cacheKey: brandCacheKey(version),
    expo: {
      appIcon: mobileProjectPath(mobile.appIcon),
      splashLogo: mobileProjectPath(mobile.splashLogo),
      favicon: mobileProjectPath(mobile.favicon),
      androidStoreIcon: mobileProjectPath(mobile.androidStoreIcon),
      adaptiveForeground: mobileProjectPath(mobile.adaptiveForeground),
      adaptiveBackground: mobileProjectPath(mobile.adaptiveBackground),
      adaptiveMonochrome: mobileProjectPath(mobile.adaptiveMonochrome),
    },
    native: {
      iosAppIconSet: mobileProjectPath(mobile.nativeIosAppIconSet, {
        directory: true,
      }),
      androidResources: mobileProjectPath(mobile.nativeAndroidResources, {
        directory: true,
      }),
    },
  };
  return `${JSON.stringify(registry, null, 2)}\n`;
}

export async function renderBrandMobileImageRegistry(): Promise<string> {
  const { mobile } = brandConsumerAssets;
  const moduleDirectory = path.dirname(
    absoluteRepositoryPath(brandMobileImageRegistryDestination),
  );
  const requirePath = (destination: string) => {
    assertMappedDestination(destination);
    const relative = path
      .relative(moduleDirectory, absoluteRepositoryPath(destination))
      .replaceAll(path.sep, "/");
    return relative.startsWith(".") ? relative : `./${relative}`;
  };
  return format(
    `/** GENERATED by scripts/sync-brand-assets.ts. Do not edit manually. */\nimport type { ImageSourcePropType } from "react-native";\n\nexport const mobileBrandImages = {\n  primary: require(${JSON.stringify(requirePath(mobile.horizontalPrimary))}),\n  reverse: require(${JSON.stringify(requirePath(mobile.horizontalReverse))}),\n} satisfies Record<"primary" | "reverse", ImageSourcePropType>;\n`,
    { parser: "typescript" },
  );
}

export function absoluteRepositoryPath(relative: string): string {
  const target = path.resolve(repositoryRoot, relative);
  const rootWithSeparator = `${repositoryRoot}${path.sep}`;
  if (!target.startsWith(rootWithSeparator)) {
    throw new Error(`Managed brand path escapes the repository: ${relative}`);
  }
  return target;
}

export function canonicalBrandPath(relative: string): string {
  const target = path.resolve(brandSourceRoot, relative);
  const rootWithSeparator = `${brandSourceRoot}${path.sep}`;
  if (
    path.isAbsolute(relative) ||
    relative.split(/[\\/]/).includes("..") ||
    !target.startsWith(rootWithSeparator)
  ) {
    throw new Error(`Canonical brand path escapes the active kit: ${relative}`);
  }
  return target;
}
