#!/usr/bin/env node
/**
 * Derives a new canonical brand-kit release from the active one with another
 * canonical orange.
 *
 * The kit is flat raster artwork generated by tooling, so a colour change is
 * a re-tint of every orange pixel (`brand-kit-retint.ts`), a regeneration of
 * the files derived from the masters (print PDF and EPS, the approximate
 * CMYK TIFF, the SVG wrappers, the favicon container, the visual preview,
 * the guidelines documents) and a rewrite of every token and manifest that
 * names the colour. Nothing is redrawn: geometry, sizes and formats are the
 * previous release's, only the orange changes.
 *
 * Usage:
 *   node --import tsx scripts/brand-kit-release.ts \
 *     --from 1.0.0 --to 1.1.0 --orange "#A54200" --date 2026-09-19
 *
 * The new release is written to brand/shongre/v<to>/ and must then be made
 * active in brand/shongre/brand.config.json and synchronised with
 * `npm run brand:sync`.
 */
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import {
  access,
  cp,
  mkdir,
  mkdtemp,
  readdir,
  readFile,
  rename,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { deflateSync } from "node:zlib";
import sharp from "sharp";
import {
  brandSourceRootForVersion,
  normalizeBrandVersion,
} from "./brand-assets.config";
import { validateBrandKit } from "./brand-kit-validation";
import { parseRgb, retintRgba, type Rgb } from "./brand-kit-retint";

interface ReleaseInput {
  from: string;
  to: string;
  orange: string;
  date: string;
}

function argument(name: string): string | undefined {
  const index = process.argv.indexOf(name);
  return index === -1 ? undefined : process.argv[index + 1];
}

function readInput(): ReleaseInput {
  const from = argument("--from");
  const to = argument("--to");
  const orange = argument("--orange");
  const date = argument("--date") ?? new Date().toISOString().slice(0, 10);
  if (!from || !to || !orange) {
    throw new Error(
      "Usage: brand-kit-release.ts --from <version> --to <version> --orange <#RRGGBB> [--date YYYY-MM-DD]",
    );
  }
  if (!/^#[\da-f]{6}$/i.test(orange)) {
    throw new Error(
      `--orange must be a six-digit hex colour; received ${orange}.`,
    );
  }
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
    throw new Error(`--date must be YYYY-MM-DD; received ${date}.`);
  }
  return {
    from: normalizeBrandVersion(from),
    to: normalizeBrandVersion(to),
    orange: orange.toUpperCase(),
    date,
  };
}

const FRENCH_MONTHS = [
  "janvier",
  "février",
  "mars",
  "avril",
  "mai",
  "juin",
  "juillet",
  "août",
  "septembre",
  "octobre",
  "novembre",
  "décembre",
];
const ENGLISH_MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

/** The guidelines write dates without diacritics ("4 septembre 2026"). */
function frenchDate(date: string): string {
  const [, month, day] = date.split("-").map(Number);
  return `${day} ${FRENCH_MONTHS[month - 1]
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")} ${date.slice(0, 4)}`;
}

function englishDate(date: string): string {
  const [, month, day] = date.split("-").map(Number);
  return `${day} ${ENGLISH_MONTHS[month - 1]} ${date.slice(0, 4)}`;
}

/** The kit's "approximate CMYK", the naive conversion its tables use. */
function cmykApproximation([red, green, blue]: Rgb): string {
  const r = red / 255;
  const g = green / 255;
  const b = blue / 255;
  const k = 1 - Math.max(r, g, b);
  const channel = (value: number) =>
    k === 1 ? 0 : Math.round(((1 - value - k) / (1 - k)) * 100);
  return `${channel(r)}, ${channel(g)}, ${channel(b)}, ${Math.round(k * 100)}`;
}

function hexOf([red, green, blue]: Rgb): string {
  return `#${[red, green, blue]
    .map((value) => value.toString(16).padStart(2, "0"))
    .join("")}`.toUpperCase();
}

async function filesUnder(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map(async (entry) => {
      const target = path.join(directory, entry.name);
      return entry.isDirectory() ? filesUnder(target) : [target];
    }),
  );
  return nested.flat().sort();
}

async function pathExists(target: string): Promise<boolean> {
  try {
    await access(target);
    return true;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return false;
    throw error;
  }
}

interface Palette {
  from: Rgb;
  to: Rgb;
  partners: readonly Rgb[];
}

/* ------------------------------------------------------------------------ */
/* Raster re-tinting                                                         */
/* ------------------------------------------------------------------------ */

async function retintRaw(
  input: Buffer | string,
  palette: Palette,
  tolerance: number,
): Promise<{ data: Buffer; width: number; height: number; changed: number }> {
  const { data, info } = await sharp(input)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  const changed = retintRgba(data, { ...palette, tolerance });
  return { data, width: info.width, height: info.height, changed };
}

function fromRaw(data: Buffer, width: number, height: number) {
  return sharp(data, { raw: { width, height, channels: 4 } });
}

async function regenerateBrandBoard(
  file: string,
  orange: string,
  ink: string,
  background: string,
): Promise<void> {
  const metadata = await sharp(file).metadata();
  if (metadata.width !== 2400 || metadata.height !== 1600) {
    throw new Error(
      `Brand-board geometry changed; expected 2400x1600 and received ${metadata.width ?? "unknown"}x${metadata.height ?? "unknown"}.`,
    );
  }

  // The palette caption is embedded in the raster rather than represented by
  // an editable token. Repaint only its established caption box after the
  // orange pixels have been re-tinted so the preview cannot advertise the
  // previous release's hex value.
  const captionLeft = 800;
  const captionTop = 1438;
  const captionWidth = 260;
  const captionHeight = 70;
  const captionBackground = await sharp({
    create: {
      width: captionWidth,
      height: captionHeight,
      channels: 4,
      background,
    },
  })
    .png()
    .toBuffer();
  const caption = Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${captionWidth}" height="${captionHeight}" viewBox="0 0 ${captionWidth} ${captionHeight}">
      <text x="24" y="51" fill="${ink}" font-family="Arial, Helvetica, sans-serif" font-size="44" font-weight="400" letter-spacing="1.5">${orange}</text>
    </svg>`,
  );

  await writeFile(
    file,
    await sharp(file)
      .composite([
        { input: captionBackground, left: captionLeft, top: captionTop },
        { input: caption, left: captionLeft, top: captionTop },
      ])
      .png({ compressionLevel: 9, adaptiveFiltering: true })
      .toBuffer(),
  );
}

async function retintPng(file: string, palette: Palette): Promise<number> {
  const { data, width, height, changed } = await retintRaw(file, palette, 3);
  if (!changed) return 0;
  await writeFile(
    file,
    await fromRaw(data, width, height)
      .png({ compressionLevel: 9, adaptiveFiltering: true })
      .toBuffer(),
  );
  return changed;
}

async function retintJpeg(file: string, palette: Palette): Promise<number> {
  const { data, width, height, changed } = await retintRaw(file, palette, 12);
  if (!changed) return 0;
  await writeFile(
    file,
    await fromRaw(data, width, height)
      .flatten({ background: "#FFFFFF" })
      .jpeg({ quality: 96, chromaSubsampling: "4:4:4" })
      .toBuffer(),
  );
  return changed;
}

async function retintWebp(file: string, palette: Palette): Promise<number> {
  const { data, width, height, changed } = await retintRaw(file, palette, 8);
  if (!changed) return 0;
  await writeFile(
    file,
    await fromRaw(data, width, height).webp({ lossless: true }).toBuffer(),
  );
  return changed;
}

async function retintTiff(file: string, palette: Palette): Promise<number> {
  const metadata = await sharp(file).metadata();
  if (metadata.space !== "srgb") return 0;
  const { data, width, height, changed } = await retintRaw(file, palette, 3);
  if (!changed) return 0;
  await writeFile(
    file,
    await fromRaw(data, width, height)
      .withMetadata({ density: metadata.density ?? 300 })
      .tiff({ compression: "deflate" })
      .toBuffer(),
  );
  return changed;
}

/**
 * The favicon container holds 32-bit BGRA device-independent bitmaps
 * (bottom-up rows, then an AND mask), so the pixels are re-tinted in place
 * and the file keeps its exact layout.
 */
async function retintIco(file: string, palette: Palette): Promise<number> {
  const ico = await readFile(file);
  const count = ico.readUInt16LE(4);
  let changed = 0;
  for (let index = 0; index < count; index += 1) {
    const entry = 6 + index * 16;
    const offset = ico.readUInt32LE(entry + 12);
    if (
      ico.readUInt32LE(offset) !== 40 ||
      ico.readUInt16LE(offset + 14) !== 32
    ) {
      throw new Error(`${file}: icon ${index} is not a 32-bit DIB.`);
    }
    const width = ico.readInt32LE(offset + 4);
    const height = ico.readInt32LE(offset + 8) / 2;
    const pixels = ico.subarray(offset + 40, offset + 40 + width * height * 4);
    // BGRA → RGBA for the shared re-tint, then back.
    const rgba = Buffer.alloc(pixels.length);
    for (let i = 0; i < pixels.length; i += 4) {
      rgba[i] = pixels[i + 2];
      rgba[i + 1] = pixels[i + 1];
      rgba[i + 2] = pixels[i];
      rgba[i + 3] = pixels[i + 3];
    }
    changed += retintRgba(rgba, { ...palette, tolerance: 3 });
    for (let i = 0; i < pixels.length; i += 4) {
      pixels[i] = rgba[i + 2];
      pixels[i + 1] = rgba[i + 1];
      pixels[i + 2] = rgba[i];
    }
  }
  if (changed) await writeFile(file, ico);
  return changed;
}

/** The kit's SVGs are compatibility wrappers around an embedded PNG. */
async function retintSvg(file: string, palette: Palette): Promise<number> {
  const source = await readFile(file, "utf8");
  const match = source.match(/href="data:image\/png;base64,([^"]+)"/);
  if (!match) return 0;
  const { data, width, height, changed } = await retintRaw(
    Buffer.from(match[1], "base64"),
    palette,
    3,
  );
  if (!changed) return 0;
  const png = await fromRaw(data, width, height)
    .png({ compressionLevel: 9, adaptiveFiltering: true })
    .toBuffer();
  await writeFile(file, source.replace(match[1], png.toString("base64")));
  return changed;
}

/* ------------------------------------------------------------------------ */
/* Derived print artwork                                                     */
/* ------------------------------------------------------------------------ */

/** The approximate-CMYK print TIFF is the RGB master flattened onto white. */
async function regenerateCmykTiff(rgbSource: string, target: string) {
  const metadata = await sharp(rgbSource).metadata();
  await writeFile(
    target,
    await sharp(rgbSource)
      .flatten({ background: "#FFFFFF" })
      .toColourspace("cmyk")
      .withMetadata({ density: metadata.density ?? 300 })
      .tiff({ compression: "deflate" })
      .toBuffer(),
  );
}

/**
 * A one-page PDF placing the master on the kit's 240 × 90 mm sheet with
 * 10 mm side margins, as the previous release's ReportLab export did.
 */
async function regeneratePrintPdf(
  rgbSource: string,
  target: string,
  title: string,
) {
  const { data, info } = await sharp(rgbSource)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  const rgb = Buffer.alloc(info.width * info.height * 3);
  const alpha = Buffer.alloc(info.width * info.height);
  for (let pixel = 0, i = 0; i < data.length; i += 4, pixel += 1) {
    rgb[pixel * 3] = data[i];
    rgb[pixel * 3 + 1] = data[i + 1];
    rgb[pixel * 3 + 2] = data[i + 2];
    alpha[pixel] = data[i + 3];
  }
  const image = deflateSync(rgb);
  const mask = deflateSync(alpha);
  const pageWidth = 680.315;
  const pageHeight = 255.1181;
  const drawWidth = 623.622;
  const drawHeight = (drawWidth * info.height) / info.width;
  const content = Buffer.from(
    `q\n${drawWidth.toFixed(3)} 0 0 ${drawHeight.toFixed(4)} ${((pageWidth - drawWidth) / 2).toFixed(5)} ${((pageHeight - drawHeight) / 2).toFixed(5)} cm\n/Im0 Do\nQ\n`,
  );
  const objects: Buffer[] = [
    Buffer.from("<< /Type /Catalog /Pages 2 0 R >>"),
    Buffer.from("<< /Type /Pages /Kids [3 0 R] /Count 1 >>"),
    Buffer.from(
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /XObject << /Im0 5 0 R >> >> /Contents 4 0 R >>`,
    ),
    Buffer.concat([
      Buffer.from(`<< /Length ${content.length} >>\nstream\n`),
      content,
      Buffer.from("\nendstream"),
    ]),
    Buffer.concat([
      Buffer.from(
        `<< /Type /XObject /Subtype /Image /Width ${info.width} /Height ${info.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /FlateDecode /SMask 6 0 R /Length ${image.length} >>\nstream\n`,
      ),
      image,
      Buffer.from("\nendstream"),
    ]),
    Buffer.concat([
      Buffer.from(
        `<< /Type /XObject /Subtype /Image /Width ${info.width} /Height ${info.height} /ColorSpace /DeviceGray /BitsPerComponent 8 /Filter /FlateDecode /Length ${mask.length} >>\nstream\n`,
      ),
      mask,
      Buffer.from("\nendstream"),
    ]),
    Buffer.from(
      `<< /Title (${title}) /Producer (Shongre brand-kit release tooling) /Creator (scripts/brand-kit-release.ts) >>`,
    ),
  ];
  const parts: Buffer[] = [
    Buffer.from("%PDF-1.4\n%\xE2\xE3\xCF\xD3\n", "latin1"),
  ];
  const offsets: number[] = [];
  let position = parts[0].length;
  objects.forEach((object, index) => {
    offsets.push(position);
    const chunk = Buffer.concat([
      Buffer.from(`${index + 1} 0 obj\n`),
      object,
      Buffer.from("\nendobj\n"),
    ]);
    parts.push(chunk);
    position += chunk.length;
  });
  const xref = [
    `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`,
    ...offsets.map(
      (offset) => `${String(offset).padStart(10, "0")} 00000 n \n`,
    ),
    `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R /Info ${objects.length} 0 R >>\nstartxref\n${position}\n%%EOF\n`,
  ].join("");
  parts.push(Buffer.from(xref));
  await writeFile(target, Buffer.concat(parts));
}

/** A Level 2 EPS: the master flattened onto white as hex `colorimage` data. */
async function regenerateEps(rgbSource: string, target: string, title: string) {
  const { data, info } = await sharp(rgbSource)
    .flatten({ background: "#FFFFFF" })
    .removeAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  const rows: string[] = [];
  const rowBytes = info.width * 3;
  for (let row = 0; row < info.height; row += 1) {
    rows.push(
      data.subarray(row * rowBytes, (row + 1) * rowBytes).toString("hex"),
    );
  }
  const header = [
    "%!PS-Adobe-3.0 EPSF-3.0",
    `%%Title: (${title})`,
    "%%Creator: (scripts/brand-kit-release.ts)",
    `%%BoundingBox: 0 0 ${info.width} ${info.height}`,
    `%%HiResBoundingBox: 0 0 ${info.width} ${info.height}`,
    "%%DocumentData: Clean7Bit",
    "%%LanguageLevel: 2",
    "%%Pages: 1",
    "%%EndComments",
    "%%BeginProlog",
    "%%EndProlog",
    "%%Page: 1 1",
    "gsave",
    `/picstr ${rowBytes} string def`,
    `0 0 translate ${info.width} ${info.height} scale`,
    `${info.width} ${info.height} 8 [${info.width} 0 0 -${info.height} 0 ${info.height}]`,
    "{currentfile picstr readhexstring pop} false 3 colorimage",
  ].join("\n");
  await writeFile(
    target,
    `${header}\n${rows.join("\n")}\ngrestore\nshowpage\n%%Trailer\n%%EOF\n`,
  );
}

/* ------------------------------------------------------------------------ */
/* Documentation                                                             */
/* ------------------------------------------------------------------------ */

interface TextRewrite {
  fromHex: string;
  toHex: string;
  fromRgb: Rgb;
  toRgb: Rgb;
  fromVersion: string;
  toVersion: string;
  fromDate: string;
  toDate: string;
}

function rewriteText(source: string, rewrite: TextRewrite): string {
  const fromBare = rewrite.fromHex.slice(1);
  const toBare = rewrite.toHex.slice(1);
  const rgbText = (rgb: Rgb) => rgb.join(", ");
  return source
    .replaceAll(rewrite.fromHex, rewrite.toHex)
    .replaceAll(rewrite.fromHex.toLowerCase(), rewrite.toHex.toLowerCase())
    .replaceAll(fromBare, toBare)
    .replaceAll(fromBare.toLowerCase(), toBare.toLowerCase())
    .replaceAll(rgbText(rewrite.fromRgb), rgbText(rewrite.toRgb))
    .replaceAll(
      cmykApproximation(rewrite.fromRgb),
      cmykApproximation(rewrite.toRgb),
    )
    .replaceAll(rewrite.fromVersion, rewrite.toVersion)
    .replaceAll(rewrite.fromDate, rewrite.toDate)
    .replaceAll(frenchDate(rewrite.fromDate), frenchDate(rewrite.toDate))
    .replaceAll(englishDate(rewrite.fromDate), englishDate(rewrite.toDate));
}

/** The iOS colour set also carries the channels as floats. */
function rewriteIosColors(source: string, rewrite: TextRewrite): string {
  const float = (value: number) => Number((value / 255).toFixed(4));
  const [red, green, blue] = rewrite.toRgb;
  return rewriteText(source, rewrite).replace(
    /("shongreOrange":\s*\{"hex":\s*"#[\dA-F]{6}",\s*"red":\s*)[\d.]+(,\s*"green":\s*)[\d.]+(,\s*"blue":\s*)[\d.]+/i,
    `$1${float(red).toFixed(4)}$2${float(green).toFixed(4)}$3${float(blue).toFixed(4)}`,
  );
}

/**
 * The Word guidelines are a zip: the text is rewritten in the document part
 * and every embedded logo is re-tinted like the rest of the kit.
 */
async function rewriteDocx(
  file: string,
  rewrite: TextRewrite,
  palette: Palette,
): Promise<void> {
  const workspace = await mkdtemp(path.join(tmpdir(), "shongre-docx-"));
  try {
    execFileSync("unzip", ["-q", file, "-d", workspace]);
    const documentPart = path.join(workspace, "word", "document.xml");
    await writeFile(
      documentPart,
      rewriteText(await readFile(documentPart, "utf8"), rewrite),
    );
    const media = path.join(workspace, "word", "media");
    for (const image of await filesUnder(media).catch(() => [])) {
      if (/\.png$/i.test(image)) await retintPng(image, palette);
      else if (/\.jpe?g$/i.test(image)) await retintJpeg(image, palette);
    }
    await rm(file);
    execFileSync("zip", ["-q", "-X", "-r", file, "."], { cwd: workspace });
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
}

/** The subset of Markdown the guidelines use, rendered for a PDF export. */
function markdownToHtml(markdown: string): string {
  const escape = (value: string) =>
    value
      .replaceAll("&", "&amp;")
      .replaceAll("<", "&lt;")
      .replaceAll(">", "&gt;");
  const inline = (value: string) =>
    escape(value)
      .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
      .replace(/`([^`]+)`/g, "<code>$1</code>");
  const lines = markdown.split("\n");
  const html: string[] = [];
  let paragraph: string[] = [];
  let list: string[] = [];
  let table: string[][] = [];
  const flushParagraph = () => {
    if (paragraph.length) html.push(`<p>${inline(paragraph.join(" "))}</p>`);
    paragraph = [];
  };
  const flushList = () => {
    if (list.length)
      html.push(
        `<ul>${list.map((item) => `<li>${inline(item)}</li>`).join("")}</ul>`,
      );
    list = [];
  };
  const flushTable = () => {
    if (table.length) {
      const [head, ...body] = table;
      html.push(
        `<table><thead><tr>${head.map((cell) => `<th>${inline(cell)}</th>`).join("")}</tr></thead><tbody>${body
          .map(
            (row) =>
              `<tr>${row.map((cell) => `<td>${inline(cell)}</td>`).join("")}</tr>`,
          )
          .join("")}</tbody></table>`,
      );
    }
    table = [];
  };
  for (const line of lines) {
    const heading = line.match(/^(#{1,3})\s+(.*)$/);
    if (heading) {
      flushParagraph();
      flushList();
      flushTable();
      html.push(
        `<h${heading[1].length}>${inline(heading[2])}</h${heading[1].length}>`,
      );
      continue;
    }
    if (/^\|/.test(line)) {
      flushParagraph();
      flushList();
      if (/^\|\s*-+/.test(line)) continue;
      table.push(
        line
          .replace(/^\||\|$/g, "")
          .split("|")
          .map((cell) => cell.trim()),
      );
      continue;
    }
    const item = line.match(/^-\s+(.*)$/);
    if (item) {
      flushParagraph();
      flushTable();
      list.push(item[1]);
      continue;
    }
    if (/^\s+\S/.test(line) && list.length) {
      list[list.length - 1] += ` ${line.trim()}`;
      continue;
    }
    if (!line.trim()) {
      flushParagraph();
      flushList();
      flushTable();
      continue;
    }
    paragraph.push(line.trim());
  }
  flushParagraph();
  flushList();
  flushTable();
  return html.join("\n");
}

/** The PDF guidelines are rendered from the Markdown by headless Chromium. */
async function regenerateGuidelinesPdf(
  markdownFile: string,
  target: string,
  kitRoot: string,
  palette: Palette,
): Promise<void> {
  const { chromium } = await import("playwright");
  const markdown = await readFile(markdownFile, "utf8");
  const logo = await readFile(
    path.join(kitRoot, "01_Logo/Master/shongre-logo-horizontal-primary.png"),
  );
  const reverse = await readFile(
    path.join(
      kitRoot,
      "01_Logo/Color_Variants/shongre-logo-horizontal-reverse.png",
    ),
  );
  const icon = await readFile(
    path.join(kitRoot, "02_Icon/Master/shongre-icon-primary.png"),
  );
  const orange = hexOf(palette.to);
  const page = `<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>SHONGRE. — Charte graphique</title>
<style>
  @page { size: A4; margin: 18mm 16mm 20mm 16mm; }
  body { font-family: Inter, "Helvetica Neue", Arial, sans-serif; color: #172033; font-size: 11pt; line-height: 1.5; }
  h1 { font-size: 22pt; margin: 0 0 4pt; }
  h2 { font-size: 14pt; margin: 22pt 0 6pt; color: ${orange}; page-break-after: avoid; }
  p, li { margin: 0 0 6pt; }
  ul { padding-left: 18pt; }
  code { font-family: Menlo, Consolas, monospace; font-size: 9.5pt; background: #F7F8FA; padding: 0 3pt; border-radius: 3pt; }
  table { border-collapse: collapse; width: 100%; margin: 8pt 0 12pt; font-size: 10pt; }
  th, td { border: 1px solid #D8DDE5; padding: 5pt 7pt; text-align: left; }
  th { background: #F7F8FA; }
  .marks { display: flex; gap: 16pt; align-items: center; margin: 10pt 0 14pt; }
  .marks img { height: 44pt; }
  .marks .reverse { background: #172033; padding: 8pt 12pt; border-radius: 6pt; }
  .swatches { display: flex; gap: 8pt; margin: 6pt 0 10pt; }
  .swatch { flex: 1; height: 42pt; border: 1px solid #D8DDE5; border-radius: 4pt; }
  footer { position: fixed; bottom: 0; font-size: 8pt; color: #5B6474; }
</style></head><body>
<div class="marks">
  <img src="data:image/png;base64,${logo.toString("base64")}" alt="Logo horizontal principal">
  <span class="reverse"><img src="data:image/png;base64,${reverse.toString("base64")}" alt="Logo inversé"></span>
  <img src="data:image/png;base64,${icon.toString("base64")}" alt="Icône">
</div>
${markdownToHtml(markdown).replace(
  "<h2>3. Couleurs</h2>",
  `<h2>3. Couleurs</h2><div class="swatches"><div class="swatch" style="background:${orange}"></div><div class="swatch" style="background:#172033"></div><div class="swatch" style="background:#FFFFFF"></div><div class="swatch" style="background:#F7F8FA"></div></div>`,
)}
</body></html>`;
  const browser = await chromium.launch();
  try {
    const tab = await browser.newPage();
    await tab.setContent(page, { waitUntil: "load" });
    await tab.pdf({
      path: target,
      format: "A4",
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: "<span></span>",
      footerTemplate:
        '<div style="font-size:8px;color:#5B6474;width:100%;text-align:center;">SHONGRE. — Charte graphique — <span class="pageNumber"></span>/<span class="totalPages"></span></div>',
      margin: { top: "18mm", right: "16mm", bottom: "20mm", left: "16mm" },
    });
  } finally {
    await browser.close();
  }
}

/* ------------------------------------------------------------------------ */
/* Manifest and checksums                                                    */
/* ------------------------------------------------------------------------ */

async function digest(file: string): Promise<string> {
  return createHash("sha256")
    .update(await readFile(file))
    .digest("hex");
}

async function readPreviousManifest(kitRoot: string) {
  const rows = new Map<string, { mediaType: string; mode: string }>();
  const contents = await readFile(
    path.join(kitRoot, "ASSET_MANIFEST.csv"),
    "utf8",
  );
  for (const line of contents.trim().split(/\r?\n/).slice(1)) {
    const [relative, , mediaType, , , mode] = line.split(",");
    rows.set(relative, { mediaType, mode });
  }
  return rows;
}

async function imageDimensions(file: string, relative: string) {
  if (/\.eps$/i.test(relative)) {
    const bounds = (await readFile(file, "utf8")).match(
      /^%%HiResBoundingBox:\s+\S+\s+\S+\s+(\d+)\s+(\d+)$/m,
    );
    return bounds
      ? { width: Number(bounds[1]), height: Number(bounds[2]) }
      : {};
  }
  if (/\.ico$/i.test(relative)) {
    const ico = await readFile(file);
    const count = ico.readUInt16LE(4);
    let width = 0;
    let height = 0;
    for (let index = 0; index < count; index += 1) {
      width = Math.max(width, ico[6 + index * 16] || 256);
      height = Math.max(height, ico[7 + index * 16] || 256);
    }
    return { width, height };
  }
  if (/\.(?:png|jpe?g|webp|tiff?)$/i.test(relative)) {
    const metadata = await sharp(file).metadata();
    return { width: metadata.width, height: metadata.height };
  }
  return {};
}

async function writeManifests(
  kitRoot: string,
  previous: Map<string, { mediaType: string; mode: string }>,
) {
  const files = (await filesUnder(kitRoot)).map((file) =>
    path.relative(kitRoot, file).replaceAll(path.sep, "/"),
  );
  const manifestRows = ["path,bytes,media_type,width_px,height_px,mode,sha256"];
  for (const relative of files) {
    if (relative === "ASSET_MANIFEST.csv" || relative === "CHECKSUMS.sha256")
      continue;
    const file = path.join(kitRoot, relative);
    const sha = await digest(file);
    const known = previous.get(relative);
    if (!known) throw new Error(`No previous manifest row for ${relative}.`);
    const { width, height } = await imageDimensions(file, relative);
    manifestRows.push(
      [
        relative,
        String((await stat(file)).size),
        known.mediaType,
        width ? String(width) : "",
        height ? String(height) : "",
        known.mode,
        sha,
      ].join(","),
    );
  }
  await writeFile(
    path.join(kitRoot, "ASSET_MANIFEST.csv"),
    `${manifestRows.join("\n")}\n`,
  );
  // The checksum list covers every file, the manifest included.
  const checksumRows: string[] = [];
  for (const relative of files) {
    if (relative === "CHECKSUMS.sha256") continue;
    checksumRows.push(
      `${await digest(path.join(kitRoot, relative))}  ${relative}`,
    );
  }
  await writeFile(
    path.join(kitRoot, "CHECKSUMS.sha256"),
    `${checksumRows.join("\n")}\n`,
  );
}

/* ------------------------------------------------------------------------ */
/* Release                                                                   */
/* ------------------------------------------------------------------------ */

async function release(input: ReleaseInput): Promise<void> {
  const sourceRoot = brandSourceRootForVersion(input.from);
  const finalRoot = brandSourceRootForVersion(input.to);
  if (sourceRoot === finalRoot) {
    throw new Error("Source and target brand versions must differ.");
  }
  if (!(await pathExists(sourceRoot))) {
    throw new Error(`Source brand kit v${input.from} does not exist.`);
  }
  if (await pathExists(finalRoot)) {
    throw new Error(
      `Brand kit v${input.to} already exists and released kits are immutable.`,
    );
  }
  await mkdir(path.dirname(finalRoot), { recursive: true });
  const kitRoot = await mkdtemp(
    path.join(path.dirname(finalRoot), `.brand-release-v${input.to}-`),
  );
  let published = false;
  try {
    const tokens = JSON.parse(
      await readFile(
        path.join(sourceRoot, "08_Design_Tokens/brand-tokens.json"),
        "utf8",
      ),
    ) as { color: Record<string, { value: string }> };
    const fromHex = tokens.color.orange.value.toUpperCase();
    if (fromHex === input.orange) {
      throw new Error(`Release v${input.from} already uses ${input.orange}.`);
    }
    const palette: Palette = {
      from: parseRgb(fromHex),
      to: parseRgb(input.orange),
      partners: ["white", "ink", "mist", "border", "muted"]
        .filter((name) => tokens.color[name])
        .map((name) => parseRgb(tokens.color[name].value)),
    };
    const versionText = await readFile(
      path.join(sourceRoot, "VERSION.txt"),
      "utf8",
    );
    const fromDate = versionText.match(
      /^Release date:\s*(\d{4}-\d{2}-\d{2})/m,
    )?.[1];
    if (!fromDate) throw new Error("VERSION.txt has no release date.");
    const rewrite: TextRewrite = {
      fromHex,
      toHex: input.orange,
      fromRgb: palette.from,
      toRgb: palette.to,
      fromVersion: input.from,
      toVersion: input.to,
      fromDate,
      toDate: input.date,
    };

    await cp(sourceRoot, kitRoot, { recursive: true });
    const previousManifest = await readPreviousManifest(kitRoot);

    const report = {
      retinted: [] as string[],
      regenerated: [] as string[],
      rewritten: [] as string[],
    };
    for (const file of await filesUnder(kitRoot)) {
      const relative = path.relative(kitRoot, file).replaceAll(path.sep, "/");
      let changed = 0;
      if (/\.png$/i.test(relative)) changed = await retintPng(file, palette);
      else if (/\.jpe?g$/i.test(relative))
        changed = await retintJpeg(file, palette);
      else if (/\.webp$/i.test(relative))
        changed = await retintWebp(file, palette);
      else if (/\.tiff?$/i.test(relative))
        changed = await retintTiff(file, palette);
      else if (/\.ico$/i.test(relative))
        changed = await retintIco(file, palette);
      else if (/\.svg$/i.test(relative))
        changed = await retintSvg(file, palette);
      if (changed) report.retinted.push(relative);
    }

    // The lossy raster exports are re-derived from the lossless master next to
    // them rather than re-tinted from their own decoded noise.
    const rasterMaster = path.join(
      kitRoot,
      "01_Logo/Raster/shongre-logo-horizontal.tif",
    );
    await writeFile(
      path.join(kitRoot, "01_Logo/Raster/shongre-logo-horizontal.webp"),
      await sharp(rasterMaster).webp({ lossless: true }).toBuffer(),
    );
    await writeFile(
      path.join(kitRoot, "01_Logo/Raster/shongre-logo-horizontal-on-white.jpg"),
      await sharp(rasterMaster)
        .flatten({ background: hexOf(parseRgb(tokens.color.white.value)) })
        .jpeg({ quality: 96, chromaSubsampling: "4:4:4" })
        .toBuffer(),
    );
    await writeFile(
      path.join(kitRoot, "01_Logo/Raster/shongre-logo-horizontal-on-ink.jpg"),
      await sharp(rasterMaster)
        .flatten({ background: hexOf(parseRgb(tokens.color.ink.value)) })
        .jpeg({ quality: 96, chromaSubsampling: "4:4:4" })
        .toBuffer(),
    );
    report.regenerated.push(
      "01_Logo/Raster/shongre-logo-horizontal.webp",
      "01_Logo/Raster/shongre-logo-horizontal-on-white.jpg",
      "01_Logo/Raster/shongre-logo-horizontal-on-ink.jpg",
    );

    await regenerateBrandBoard(
      path.join(kitRoot, "10_Previews/shongre-brand-board.png"),
      input.orange,
      hexOf(parseRgb(tokens.color.ink.value)),
      hexOf(parseRgb(tokens.color.mist.value)),
    );
    report.regenerated.push("10_Previews/shongre-brand-board.png");

    const rgbMaster = path.join(
      kitRoot,
      "07_Print/shongre-logo-horizontal-rgb-300dpi.tif",
    );
    await regenerateCmykTiff(
      rgbMaster,
      path.join(
        kitRoot,
        "07_Print/shongre-logo-horizontal-cmyk-approx-300dpi.tif",
      ),
    );
    await regeneratePrintPdf(
      rgbMaster,
      path.join(kitRoot, "07_Print/shongre-logo-horizontal-primary.pdf"),
      "SHONGRE. - Logo horizontal principal",
    );
    await regenerateEps(
      rgbMaster,
      path.join(kitRoot, "07_Print/shongre-logo-horizontal-primary.eps"),
      "SHONGRE. - Logo horizontal principal",
    );
    report.regenerated.push(
      "07_Print/shongre-logo-horizontal-cmyk-approx-300dpi.tif",
      "07_Print/shongre-logo-horizontal-primary.pdf",
      "07_Print/shongre-logo-horizontal-primary.eps",
    );

    for (const relative of [
      "VERSION.txt",
      "README.md",
      "08_Design_Tokens/brand-tokens.json",
      "08_Design_Tokens/shongre-brand.css",
      "08_Design_Tokens/android/colors.xml",
      "05_Android/app/src/main/res/values/colors.xml",
      "03_Web/site.webmanifest",
      "09_Documentation/Shongre_Brand_Guidelines.md",
    ]) {
      const file = path.join(kitRoot, relative);
      await writeFile(file, rewriteText(await readFile(file, "utf8"), rewrite));
      report.rewritten.push(relative);
    }
    const iosColors = path.join(kitRoot, "08_Design_Tokens/ios/Colors.json");
    await writeFile(
      iosColors,
      rewriteIosColors(await readFile(iosColors, "utf8"), rewrite),
    );
    report.rewritten.push("08_Design_Tokens/ios/Colors.json");

    await rewriteDocx(
      path.join(kitRoot, "09_Documentation/Shongre_Brand_Guidelines.docx"),
      rewrite,
      palette,
    );
    await regenerateGuidelinesPdf(
      path.join(kitRoot, "09_Documentation/Shongre_Brand_Guidelines.md"),
      path.join(kitRoot, "09_Documentation/Shongre_Brand_Guidelines.pdf"),
      kitRoot,
      palette,
    );
    report.regenerated.push(
      "09_Documentation/Shongre_Brand_Guidelines.docx",
      "09_Documentation/Shongre_Brand_Guidelines.pdf",
    );

    await writeManifests(kitRoot, previousManifest);
    await rename(kitRoot, finalRoot);
    published = true;
    const validation = await validateBrandKit(input.to);
    console.log(
      `Brand kit v${input.to} derived from v${input.from} in ${input.orange}: ${report.retinted.length} artwork files re-tinted, ${report.regenerated.length} derived files regenerated, ${report.rewritten.length + 1} token/document files rewritten, ${validation.checksummedFiles} checksums validated.`,
    );
  } catch (error) {
    await rm(published ? finalRoot : kitRoot, { recursive: true, force: true });
    throw error;
  }
}

release(readInput()).catch((error: unknown) => {
  console.error((error as Error).message);
  process.exit(1);
});
