import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { format } from "prettier";
import {
  BRAND_SIGNATURE,
  BRAND_VERSION,
  brandSourceRoot,
  repositoryRoot,
} from "./brand-assets.config";

export async function sha256(file: string): Promise<string> {
  return createHash("sha256")
    .update(await readFile(file))
    .digest("hex");
}

export async function readCanonicalChecksums(): Promise<Map<string, string>> {
  const contents = await readFile(
    path.join(brandSourceRoot, "CHECKSUMS.sha256"),
    "utf8",
  );
  const checksums = new Map<string, string>();
  for (const line of contents.split(/\r?\n/)) {
    if (!line.trim()) continue;
    const match = line.match(/^([a-f\d]{64})\s+\*?(.+)$/i);
    if (!match) throw new Error(`Invalid checksum entry: ${line}`);
    const relative = match[2].replaceAll("\\", "/");
    if (relative.startsWith("/") || relative.split("/").includes("..")) {
      throw new Error(`Unsafe checksum path: ${relative}`);
    }
    checksums.set(relative, match[1].toLowerCase());
  }
  return checksums;
}

export async function validateCanonicalChecksums(): Promise<void> {
  const checksums = await readCanonicalChecksums();
  for (const [relative, expected] of checksums) {
    const actual = await sha256(path.join(brandSourceRoot, relative));
    if (actual !== expected) {
      throw new Error(
        `Brand source checksum mismatch for ${relative}: expected ${expected}, received ${actual}.`,
      );
    }
  }
}

interface CanonicalBrandTokens {
  brand: { signature: string; version: string };
  color: Record<string, { value: string; type: string }>;
}

export async function renderBrandTokenAdapter(source: string): Promise<string> {
  const tokens = JSON.parse(
    await readFile(path.join(brandSourceRoot, source), "utf8"),
  ) as CanonicalBrandTokens;
  if (
    tokens.brand.signature !== BRAND_SIGNATURE ||
    tokens.brand.version !== BRAND_VERSION
  ) {
    throw new Error(
      `Brand token identity must be ${BRAND_SIGNATURE} v${BRAND_VERSION}.`,
    );
  }
  const required = ["orange", "ink", "white", "mist", "border", "muted"];
  for (const name of required) {
    if (!/^#[A-F\d]{6}$/i.test(tokens.color[name]?.value ?? "")) {
      throw new Error(`Brand token color.${name} is missing or invalid.`);
    }
  }
  return format(
    `/**\n * GENERATED by scripts/sync-brand-assets.ts from\n * brand/shongre/v${BRAND_VERSION}/${source}. Do not edit manually.\n */\nexport const brandIdentity = ${JSON.stringify(
      {
        signature: tokens.brand.signature,
        version: tokens.brand.version,
      },
      null,
      2,
    )};\n\nexport const brandPalette = ${JSON.stringify(
      Object.fromEntries(
        required.map((name) => [name, tokens.color[name].value.toUpperCase()]),
      ),
      null,
      2,
    )};\n`,
    { parser: "babel" },
  );
}

export async function renderBrandTokenTypes(source: string): Promise<string> {
  const adapter = await renderBrandTokenAdapter(source);
  const signature = adapter.match(/signature:\s*"([^"]+)"/)?.[1];
  const version = adapter.match(/version:\s*"([^"]+)"/)?.[1];
  const entries = [...adapter.matchAll(/^\s{2}(\w+):\s*"(#[A-F\d]{6})",?$/gim)];
  if (!signature || !version || entries.length === 0) {
    throw new Error("Unable to derive brand token declarations.");
  }
  return format(
    `/** GENERATED by scripts/sync-brand-assets.ts. Do not edit manually. */\nexport declare const brandIdentity: { readonly signature: ${JSON.stringify(signature)}; readonly version: ${JSON.stringify(version)} };\nexport declare const brandPalette: { ${entries
      .map(
        ([, name, value]) =>
          `readonly ${name}: ${JSON.stringify(value.toUpperCase())};`,
      )
      .join(" ")} };\n`,
    { parser: "typescript" },
  );
}

export async function renderBrandDocumentAdapter(
  source: string,
): Promise<string> {
  const encoded = (await readFile(path.join(brandSourceRoot, source))).toString(
    "base64",
  );
  return format(
    `/**\n * GENERATED by scripts/sync-brand-assets.ts from\n * brand/shongre/v${BRAND_VERSION}/${source}. Do not edit manually.\n *\n * The data URI keeps downloaded HTML invoices self-contained.\n */\nexport const brandDocumentLogoDataUri = ${JSON.stringify(
      `data:image/png;base64,${encoded}`,
    )} as const;\n`,
    { parser: "typescript" },
  );
}

export function absoluteRepositoryPath(relative: string): string {
  const target = path.resolve(repositoryRoot, relative);
  const rootWithSeparator = `${repositoryRoot}${path.sep}`;
  if (!target.startsWith(rootWithSeparator)) {
    throw new Error(`Managed brand path escapes the repository: ${relative}`);
  }
  return target;
}
