#!/usr/bin/env node

import { copyFile, mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  BRAND_VERSION,
  brandAssetMappings,
  brandDocumentAdapterDestination,
  brandDocumentLogoSource,
  brandSourceRoot,
  brandTokenAdapterDestination,
  brandTokenSource,
  brandTokenTypesDestination,
  generatedInventoryPath,
  managedLegacyBrandPaths,
  repositoryRoot,
} from "./brand-assets.config";
import {
  absoluteRepositoryPath,
  renderBrandDocumentAdapter,
  renderBrandTokenAdapter,
  renderBrandTokenTypes,
  sha256,
  validateCanonicalChecksums,
} from "./brand-assets.lib";

interface GeneratedInventory {
  version: number;
  brandVersion: string;
  generated: string[];
}

async function previousGeneratedPaths(): Promise<string[]> {
  try {
    const value = JSON.parse(
      await readFile(generatedInventoryPath, "utf8"),
    ) as GeneratedInventory;
    return Array.isArray(value.generated) ? value.generated : [];
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw error;
  }
}

async function removeManagedFile(relative: string): Promise<void> {
  try {
    await unlink(absoluteRepositoryPath(relative));
    process.stdout.write(`Removed obsolete generated asset ${relative}\n`);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
}

async function main(): Promise<void> {
  await validateCanonicalChecksums();

  const generated = [
    ...brandAssetMappings.map(({ destination }) => destination),
    brandDocumentAdapterDestination,
    brandTokenAdapterDestination,
    brandTokenTypesDestination,
  ].sort();
  const generatedSet = new Set(generated);

  for (const relative of await previousGeneratedPaths()) {
    if (!generatedSet.has(relative)) await removeManagedFile(relative);
  }
  for (const relative of managedLegacyBrandPaths)
    await removeManagedFile(relative);

  for (const mapping of brandAssetMappings) {
    const source = path.join(brandSourceRoot, mapping.source);
    const destination = absoluteRepositoryPath(mapping.destination);
    await mkdir(path.dirname(destination), { recursive: true });
    await copyFile(source, destination);
  }

  const tokenAdapter = await renderBrandTokenAdapter(brandTokenSource);
  const tokenDestination = absoluteRepositoryPath(brandTokenAdapterDestination);
  await mkdir(path.dirname(tokenDestination), { recursive: true });
  await writeFile(tokenDestination, tokenAdapter, "utf8");

  const tokenTypes = await renderBrandTokenTypes(brandTokenSource);
  const tokenTypesDestination = absoluteRepositoryPath(
    brandTokenTypesDestination,
  );
  await mkdir(path.dirname(tokenTypesDestination), { recursive: true });
  await writeFile(tokenTypesDestination, tokenTypes, "utf8");

  const documentAdapter = await renderBrandDocumentAdapter(
    brandDocumentLogoSource,
  );
  const documentDestination = absoluteRepositoryPath(
    brandDocumentAdapterDestination,
  );
  await mkdir(path.dirname(documentDestination), { recursive: true });
  await writeFile(documentDestination, documentAdapter, "utf8");

  const inventory = {
    notice:
      "GENERATED by scripts/sync-brand-assets.ts. Do not edit mapped files manually.",
    version: 1,
    brandVersion: BRAND_VERSION,
    source: path.relative(repositoryRoot, brandSourceRoot),
    generated,
    files: Object.fromEntries(
      await Promise.all(
        generated.map(async (relative) => [
          relative,
          await sha256(absoluteRepositoryPath(relative)),
        ]),
      ),
    ),
  };
  await mkdir(path.dirname(generatedInventoryPath), { recursive: true });
  await writeFile(
    generatedInventoryPath,
    `${JSON.stringify(inventory, null, 2)}\n`,
    "utf8",
  );

  process.stdout.write(
    `Synchronized ${generated.length} runtime brand assets from SHONGRE. v${BRAND_VERSION}.\n`,
  );
}

main().catch((error: unknown) => {
  process.stderr.write(
    `Brand synchronization failed: ${(error as Error).message}\n`,
  );
  process.exit(1);
});
