import type { ComplianceRule } from "@shongre/contracts/compliance";

/**
 * Versioned bootstrap registry. Database rules with the same id replace these
 * values, so policy changes and scheduled activation do not require UI edits.
 */
export const BASELINE_COMPLIANCE_RULES: readonly ComplianceRule[] = [
  {
    id: "global-browse-v1",
    jurisdiction: "*",
    regulation: "PRODUCT_BASELINE",
    ruleCode: "BROWSE_WITHOUT_IDENTIFICATION",
    description: "Public discovery must not trigger identity verification.",
    action: "browse",
    conditions: {},
    requiredChecks: [],
    recommendedChecks: [],
    reasonCodes: [],
    legalBasis: ["GDPR_DATA_MINIMISATION"],
    sourceReferences: ["https://eur-lex.europa.eu/eli/reg/2016/679/oj"],
    policyVersion: "baseline-2026.1",
    governance: "LEGAL_MANDATE",
    status: "ACTIVE",
    effectiveFrom: "2024-02-17T00:00:00.000Z",
    priority: 100,
  },
  ...(["create_account", "save_favorite", "message_seller"] as const).map(
    (action, index): ComplianceRule => ({
      id: `global-${action}-email-v1`,
      jurisdiction: "*",
      regulation: "ACCOUNT_SECURITY",
      ruleCode: `EMAIL_FOR_${action.toUpperCase()}`,
      description: "A confirmed account is sufficient for this interaction.",
      action,
      conditions: { accountTypes: ["individual", "professional"] },
      requiredChecks: ["email"],
      recommendedChecks: action === "message_seller" ? ["phone"] : [],
      reasonCodes: ["ACCOUNT_CONFIRMATION_REQUIRED"],
      legalBasis: ["CONTRACT", "LEGITIMATE_INTEREST_ACCOUNT_SECURITY"],
      sourceReferences: [],
      policyVersion: "baseline-2026.1",
      governance: "BUSINESS_POLICY",
      status: "ACTIVE",
      effectiveFrom: "2026-01-01T00:00:00.000Z",
      priority: 50 - index,
    }),
  ),
  {
    id: "fr-private-listing-v1",
    jurisdiction: "FR",
    regulation: "MARKETPLACE_PUBLICATION",
    ruleCode: "PRIVATE_ORDINARY_LISTING",
    description: "An ordinary private classified listing requires only a confirmed account.",
    action: "publish_listing",
    conditions: { accountTypes: ["individual"], sellerTypes: ["individual"] },
    requiredChecks: ["email", "professional_status"],
    recommendedChecks: ["phone"],
    reasonCodes: ["SELLER_CLASSIFICATION_REQUIRED"],
    legalBasis: ["CONTRACT", "LEGITIMATE_INTEREST_MARKETPLACE_SAFETY"],
    sourceReferences: [],
    policyVersion: "fr-2026.1",
    governance: "BUSINESS_POLICY",
    status: "ACTIVE",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    priority: 60,
  },
  {
    id: "global-promote-listing-v1",
    jurisdiction: "*",
    regulation: "MARKETPLACE_PROMOTION",
    ruleCode: "PROMOTION_CONFIRMED_ACCOUNT",
    description: "Promotion requires only the confirmed owner of an eligible listing.",
    action: "promote_listing",
    conditions: { accountTypes: ["individual", "professional"] },
    requiredChecks: ["email"],
    recommendedChecks: [],
    reasonCodes: ["LISTING_OWNER_CONFIRMATION_REQUIRED"],
    legalBasis: ["CONTRACT"],
    sourceReferences: [],
    policyVersion: "baseline-2026.1",
    governance: "BUSINESS_POLICY",
    status: "ACTIVE",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    priority: 50,
  },
  {
    id: "fr-create-organization-v1",
    jurisdiction: "FR",
    regulation: "BUSINESS_ACCOUNT",
    ruleCode: "CREATE_PROFESSIONAL_ORGANIZATION",
    description: "Creating a professional organization verifies the business and representative authority once.",
    action: "create_organization",
    conditions: { accountTypes: ["professional"], sellerTypes: ["professional"] },
    requiredChecks: ["email", "business", "business_representative"],
    recommendedChecks: ["phone"],
    reasonCodes: ["ORGANIZATION_AUTHORITY_REQUIRED"],
    legalBasis: ["CONTRACT", "LEGITIMATE_INTEREST_ACCOUNT_SECURITY"],
    sourceReferences: [],
    policyVersion: "fr-2026.1",
    governance: "BUSINESS_POLICY",
    status: "ACTIVE",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    priority: 70,
  },
  {
    id: "fr-professional-listing-v1",
    jurisdiction: "FR",
    regulation: "TRADER_TRACEABILITY",
    ruleCode: "PROFESSIONAL_PUBLICATION_BASELINE",
    description: "Professional publication requires a verified business and representative authority.",
    action: "publish_professional_listing",
    conditions: {
      accountTypes: ["professional"],
      sellerTypes: ["professional"],
    },
    requiredChecks: [
      "email",
      "business",
      "business_representative",
      "professional_status",
    ],
    recommendedChecks: ["phone", "vat"],
    reasonCodes: ["PROFESSIONAL_SELLER_TRACEABILITY"],
    legalBasis: ["DSA_ARTICLE_30_WHERE_APPLICABLE", "CONSUMER_INFORMATION"],
    sourceReferences: ["https://eur-lex.europa.eu/eli/reg/2022/2065/oj"],
    policyVersion: "fr-dsa-2026.1",
    governance: "LEGAL_MANDATE",
    status: "ACTIVE",
    effectiveFrom: "2024-02-17T00:00:00.000Z",
    priority: 80,
  },
  {
    id: "fr-risk-elevated-phone-v1",
    jurisdiction: "FR",
    regulation: "FRAUD_PREVENTION",
    ruleCode: "ELEVATED_RISK_STEP_UP",
    description: "Proportionate contact verification for elevated-risk interactions.",
    action: "message_seller",
    conditions: { riskLevels: ["ELEVATED", "HIGH", "CRITICAL"] },
    requiredChecks: ["phone"],
    recommendedChecks: [],
    reasonCodes: ["RISK_STEP_UP_CONTACT"],
    legalBasis: ["LEGITIMATE_INTEREST_FRAUD_PREVENTION"],
    sourceReferences: [],
    policyVersion: "risk-2026.1",
    governance: "RISK_CONTROL",
    status: "ACTIVE",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    priority: 90,
  },
  {
    id: "fr-risk-high-review-v1",
    jurisdiction: "FR",
    regulation: "FRAUD_PREVENTION",
    ruleCode: "HIGH_RISK_HUMAN_REVIEW",
    description: "High-risk publication requires a reviewable step-up, not an opaque permanent ban.",
    action: "publish_listing",
    conditions: { riskLevels: ["HIGH", "CRITICAL"] },
    requiredChecks: ["phone", "enhanced_review"],
    recommendedChecks: ["identity"],
    reasonCodes: ["RISK_STEP_UP_PUBLICATION", "HUMAN_REVIEW_AVAILABLE"],
    legalBasis: ["LEGITIMATE_INTEREST_FRAUD_PREVENTION"],
    sourceReferences: [],
    policyVersion: "risk-2026.1",
    governance: "RISK_CONTROL",
    status: "ACTIVE",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    priority: 95,
  },
  {
    id: "fr-psp-payment-v1",
    jurisdiction: "FR",
    regulation: "PAYMENT_SERVICES",
    ruleCode: "PSP_SELLER_PAYMENT_ENABLEMENT",
    description: "Online payment enablement is delegated to a regulated PSP compliance account.",
    action: "accept_online_payment",
    conditions: { paymentFlows: ["psp_marketplace", "redirect_to_psp"] },
    requiredChecks: ["email", "payment"],
    recommendedChecks: ["phone"],
    reasonCodes: ["PAYMENT_PROVIDER_REQUIREMENTS"],
    legalBasis: ["PSP_REGULATORY_REQUIREMENTS"],
    sourceReferences: [
      "https://acpr.banque-france.fr/fr/professionnels/lacpr-vous-accompagne/parcours-fintech/contenus-pedagogiques/de-quel-statut-releve-mon-activite/jencaisse-des-fonds-et-les-reverse-une-tierce-personne",
    ],
    policyVersion: "payments-2026.1",
    governance: "LEGAL_MANDATE",
    status: "ACTIVE",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    priority: 100,
  },
  ...(["individual", "professional"] as const).map(
    (sellerType): ComplianceRule => ({
      id: `fr-payout-${sellerType}-v1`,
      jurisdiction: "FR",
      regulation: "PAYMENT_SERVICES",
      ruleCode: `PSP_PAYOUT_${sellerType.toUpperCase()}`,
      description: "Only payout is blocked while the PSP completes its checks.",
      action: "receive_payout",
      conditions: { sellerTypes: [sellerType], paymentFlows: ["psp_marketplace"] },
      requiredChecks:
        sellerType === "individual"
          ? ["email", "identity", "bank_account", "payout"]
          : [
              "email",
              "business",
              "business_representative",
              "bank_account",
              "payout",
            ],
      recommendedChecks: ["phone"],
      reasonCodes: ["PAYOUT_PROVIDER_REQUIREMENTS"],
      legalBasis: ["PSP_REGULATORY_REQUIREMENTS"],
      sourceReferences: [
        "https://acpr.banque-france.fr/fr/professionnels/lacpr-vous-accompagne/parcours-fintech/contenus-pedagogiques/de-quel-statut-releve-mon-activite/jencaisse-des-fonds-et-les-reverse-une-tierce-personne",
      ],
      policyVersion: "payments-2026.1",
      governance: "LEGAL_MANDATE",
      status: "ACTIVE",
      effectiveFrom: "2026-01-01T00:00:00.000Z",
      priority: 100,
    }),
  ),
  {
    id: "fr-dac7-due-diligence-review-v1",
    jurisdiction: "FR",
    regulation: "DAC7_DPI",
    ruleCode: "FACILITATED_ACTIVITY_DUE_DILIGENCE",
    description: "Tax due diligence is triggered only after the activity is determined to be in scope.",
    action: "complete_tax_due_diligence",
    conditions: {
      transactionTypes: ["direct_purchase", "service_booking", "reservation"],
      contractConclusionModes: ["platform", "unknown"],
    },
    requiredChecks: [],
    recommendedChecks: ["tax", "address"],
    reasonCodes: ["DAC7_APPLICABILITY_MUST_BE_CONFIRMED"],
    legalBasis: ["DAC7_DPI_WHERE_APPLICABLE"],
    sourceReferences: [
      "https://eur-lex.europa.eu/eli/dir/2021/514/oj",
      "https://bofip.impots.gouv.fr/bofip/13729-PGP.html/identifiant=BOI-INT-AEA-30-10-20230111",
    ],
    policyVersion: "fr-dac7-2026.1",
    governance: "LEGAL_MANDATE",
    status: "LEGAL_REVIEW_REQUIRED",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    priority: 100,
  },
] as const;
